### ISSUE TITLE
A program to find minimum number of changes to make a bit string with alternate values.

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#1]
# Feature ✅

## Example:
Input: 011101

Output: 1

Input: 100101000

Output:3

In sample 2, If 101010.. template is followed 6 changes are needed but for 0101.. only 3 changes are required.
__Mention programming language while requesting assignment__

**Comment by sauravUppoor** [comment]
@pratik-choudhari I would like to work on this problem. Language: C++
