### ISSUE TITLE
Find primes less than a number

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#10]
# Feature ✅

## Description
Print all primes less than or equal to a given number

## Example
Input: 27
Output: 2 3 5 7 11 13 17 19 23

__Hint: Look up for Sieve of Eratosthenes__

**Comment by Rr8eezz4aa** [comment]
Hi, please assign it to me!

**Comment by pratik-choudhari** [comment]
@Rr8eezz4aa Please mention the language you will be using.

**Comment by Rr8eezz4aa** [comment]
Python and Java

**Comment by pratik-choudhari** [comment]
@Rr8eezz4aa You can only choose one!

**Comment by Rr8eezz4aa** [comment]
Python

**Comment by tejaswini22199** [comment]
Hey pratik-choudari I want to solve this in C++,Could you please assign it to me?

**Comment by tejaswini22199** [comment]
Thank you @pratik-choudhari

**Comment by statst** [comment]
Can I contribute. Language: Javascript

**Comment by pratik-choudhari** [comment]
@statst You are up!
