### ISSUE TITLE
Identify floating point numbers

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#104]
# Feature ✅

## Description
Identify floating point numbers.

## Example
Input: +4.00
Output: Yes

Input: +-5.00
Output: No

Input: -.7
Output: Yes

Input: 12.
Output: No

Input: 12.o0
Output: No

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by shashankseth01** [comment]
I will give the solution in c++

**Comment by TechnoPhasePRO** [comment]
@pratik-choudhari  i would like to do this in python. please assign this to me.

**Comment by TechnoPhasePRO** [comment]
@pratik-choudhari Sir, please check & merge the pull request.

**Comment by TechnoPhasePRO** [comment]
@pratik-choudhari sir, i have created another directory in python folder. Please check it out & merge the pull request.

**Comment by TechnoPhasePRO** [comment]
@pratik-choudhari sir, i have created this new PR #164 and renamed the file of python and included readme file. Please merge the PR and provide labels to it.
