### ISSUE TITLE
IP validation using Regex

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#106]
# Feature ✅

## Description
Identify valid IP address using the power of regex.
`IP address is a string in the form "A.B.C.D", where the value of A, B, C, and D may range from 0 to 255. Leading zeros are allowed. The length of A, B, C, or D can't be greater than 3.`

## Example
First line is number of test cases.
Input:
6
000.12.12.034
121.234.12.12
23.45.12.56
00.12.123.123123.123
122.23
Hello.IP

Output:
true
true
true
false
false
false

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by megabyte98** [comment]
can you please assign this issue to me I would like to implement this using python

**Comment by statst** [comment]
Can I contribute. Language: Javascript

**Comment by Grasstown** [comment]
Can I contribute to this by implementing a Java solution?

**Comment by AlessandroArosio** [comment]
Can I contribute in Java?

**Comment by pratik-choudhari** [comment]
@AlessandroArosio Java has been assigned. Want to try in Go?

**Comment by AlessandroArosio** [comment]
Yeah why not, I can give it a "go" (no pun intended)

**Comment by AlessandroArosio** [comment]
Hi @pratik-choudhari ,

I'm about to create a pull request. Can you assign me the issue please? :)
