### ISSUE TITLE
Scrape dictionary.com

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#11]
# Feature ✅

## Description
The task here is to scrape dictionary.com for words and their meanings and store the scraped data into a json file.

## Example
Must be able to run the script and json file should get generated.

__Hint: In python use tqdm for updating progress__
__Mention programming language while requesting assignment__

**Comment by Blastoise** [comment]
@pratik-choudhari Can I contribute to this?

**Comment by pratik-choudhari** [comment]
@Blastoise Sure! Let me know the language.

**Comment by Blastoise** [comment]
I will be using python.

**Comment by Blastoise** [comment]
Hey @pratik-choudhari I just wanted to confirm that I have to scrape the whole dictionary.com at one go or the user will input a word that I need to scrape and store it in JSON.

**Comment by pratik-choudhari** [comment]
It should scrape all words and meaning from dictionary.com, all stored in json

**Comment by Blastoise** [comment]
Ok great! I am working on it.
