### ISSUE TITLE
Sudoku solver program 

### ISSUE THREAD

**Issue by Swarn10** [pratik-choudhari/AlgoCode#116]
# Feature ✅
**Python sudoku solver**  
## Description

**A python program to solve a Sudoku board provided by the user as input. If the board is valid it solves the board and displays the final solution, else it raises an error message that the input was invalid.**

## Example
 
**Input :-** 
![input](https://user-images.githubusercontent.com/54739905/95008708-dddbbc80-0639-11eb-94df-d6b3fc507c91.JPG)
**Note :- The 0 s here refer to the empty cells in the board**

**Output :-**
![output](https://user-images.githubusercontent.com/54739905/95008736-22675800-063a-11eb-81f0-7d02b199fd4d.JPG)
**Note :- The empty cells have been filled up with the correct digits, indicated in red**

**Comment by Swarn10** [comment]
@pratik-choudhari I want to contribute this to the repository. The programming language would be Python. Please assign it to me. Will be happy to help.

**Comment by pratik-choudhari** [comment]
@Swarn10 That's a great project. Place it under `Projects`

**Comment by VamsiMudaliar** [comment]
Can i write it in python Console application with backtracking ?

**Comment by pratik-choudhari** [comment]
@Swarn10 PR is a terminal based too

**Comment by Swarn10** [comment]
@pratik-choudhari The program is supposed to be a terminal one only. I think I made a mistake by adding under the `Projects` directory. Should I add the program under the `Python` directory ?

**Comment by pratik-choudhari** [comment]
@Swarn10 no its fine

**Comment by Swarn10** [comment]
@pratik-choudhari Let me clarify this that the program that I have added is just a normal Python program that solves the sudoku problem using backtracking. It is not like an application written in Python. So where should I add the program, under `Python` or `Projects` directory?

**Comment by pratik-choudhari** [comment]
Yes @Swarn10 I got it after seeing your PR. Put it under `Projects` add _cli to the project folder name, so one can distinguish between cli and gui

**Comment by Swarn10** [comment]
@pratik-choudhari Ok. Sure. I got it.
