### ISSUE TITLE
Closest 9's and 0's multiple

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#118]
# Feature ✅

## Description
The problem is to find the least positive multiple of input number n. The multiple must only be made up of 9's and 0's, no other digit is allowed.

## Example
First line is number of test cases.
Input:
2
3
7

Output: 
90
9009

__Challenge here is to figure out a way efficient than a brute force approach, dividing every number by n__
__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by SHARC-99** [comment]
> # Feature ✅
> ## Description
> The problem is to find the least positive multiple of input number n. The multiple must only be made up of 9's and 0's, no other digit is allowed.
> 
> ## Example
> First line is number of test cases.
> Input:
> 2
> 3
> 7
> 
> Output:
> 90
> 9009
> 
> **Challenge here is to figure out a way efficient than a brute force approach, dividing every number by n**
> **Contributors are supposed to mention their coding language while asking for assignment**

please assign this work to me!!

**Comment by pratik-choudhari** [comment]
@SHARC-99 Please mention the language

**Comment by pratik-choudhari** [comment]
@SHARC-99 Please mention the language

**Comment by AlexNorth-PNG** [comment]
@pratik-choudhari I would like to work on this using Java

**Comment by SHARC-99** [comment]
> @SHARC-99 Please mention the language

Cpp

**Comment by shivambachhety** [comment]
Python
