### ISSUE TITLE
Sum of a sequence

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#119]
# Feature ✅

## Description
Find the sum of all numbers in a sequence, where n<sup>th</sup> term is defined as:
__T<sub>n</sub> = n<sup>2</sup> - (n - 1)<sup>2</sup>__

## Example
First line defines number of terms in sequence.
Output the sequence and sum.
Input: 3

Output: 
Sequence: 1 3 5
Sum: 9

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by VamsiMudaliar** [comment]
**i would like to code in c++**

**Comment by silentwraith6** [comment]
i would like to code it in javascript

**Comment by deepjyot** [comment]
I would like to code in python

**Comment by amanraj862** [comment]
i would like to code in java and also give a try in python

**Comment by amanraj862** [comment]
Do i have to add a ReadMe too?

**Comment by dhrubajyoti89** [comment]
Can i contribute for C++?

**Comment by jayaganeshkumar** [comment]
Can I solve it in C++?

**Comment by Yashika25** [comment]
I can do this using C++ or Java. Please assign it to me so that I can start working on it.

**Comment by VamsiMudaliar** [comment]
Sir, i have my c++ code ready can i do a pr
Please assign me this task.. i unknowingly removed assignment 
Thank you !
