### ISSUE TITLE
Searching Algorithms

### ISSUE THREAD

**Issue by Siddhant-K-code** [pratik-choudhari/AlgoCode#120]
# Feature ✅

## Description
Searching Algorithms:
- [ ] Binary Search
- [ ] Fibonacci Search
- [ ] Linear Search
- [ ] Ternary Search
- [ ] Median Search

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

**Comment by silentwraith6** [comment]
i want to go for linear search

**Comment by dhrubajyoti89** [comment]
I want to contribute with binary search in C++

**Comment by Yashika25** [comment]
Please assign this issue. I can do using C++ or Java.

**Comment by pratik-choudhari** [comment]
@silentwraith6 @dhrubajyoti89 @Yashika25 All 5 need to be done by a contributor.

**Comment by dhrubajyoti89** [comment]
assign me for C++ @pratik-choudhari

**Comment by Yashika25** [comment]
> @silentwraith6 @dhrubajyoti89 @Yashika25 All 5 need to be done by a contributor.

Yes I can do all 5 please assign me for C++/Java/C.

**Comment by pratik-choudhari** [comment]
@Yashika25 for java

**Comment by VamsiMudaliar** [comment]
Please Assign me C++ @pratik-choudhari  , I can do all

**Comment by dhrubajyoti89** [comment]
i am working with c++ and will be making pr soon @VamsiMudaliar
