### ISSUE TITLE
Rotate array by D elements

### ISSUE THREAD

**Issue by mepallabiroy** [pratik-choudhari/AlgoCode#128]
#Feature ✅

## Description
Write a code to reverse the array by D elements clockwise.

## Example
1. Input: Array - 1 2 3
          D = 1
Output: 2 3 1

2. Input: Array - 5 8 9 4 2
          D = 3
Output: 4 2 5 8 9

## Checklist:

-  ✅ I have read the project guidelines.
-  ✅ I have checked all the existing projects, before submitting a new project issue.
-  ✅ This issue will be meaningful for the project.
-  ✅ I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by mepallabiroy** [comment]
Please assign me this issue. I can solve this using Python.

**Comment by dhrubajyoti89** [comment]
I can solve this using C++ @pratik-choudhari

**Comment by AlessandroArosio** [comment]
Can I solve this in Java please? If java is taken already, I'll try GoLang (or both for two PRs)

**Comment by codermind-divya** [comment]
Can I work on this in C++?

**Comment by pratik-choudhari** [comment]
@AlessandroArosio Up for Java.
@codermind-divya On FCFS basis @dhrubajyoti89 has been assigned.
