### ISSUE TITLE
Giving back🤝

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#141]
__Since the day this repository is up, 80% of the questions have been put up by me.__

__It gets difficult for a maintainer to manage the PRs, solve github doubts and do daily chores. So I request you to contribute not only the solutions but also the questions.__ 

__The type of questions being asked can be seen in the issues, feel free to experiment. Appreciate everyone who helps, thanks✌__

**Comment by ShivamYadav-Coding** [comment]
Sure!
