### ISSUE TITLE
Generate all binary strings from given pattern

### ISSUE THREAD

**Issue by ShivamYadav-Coding** [pratik-choudhari/AlgoCode#147]
# Feature ✅

## Description
Given a string containing of ‘0’, ‘1’ and ‘?’ wildcard characters, generate all binary strings that can be formed by replacing each wildcard character by ‘0’ or ‘1’.

## Example
Input str = "1??0?101"
Output: 
        10000101
        10001101
        10100101
        10101101
        11000101
        11001101
        11100101
        11101101

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by VamsiMudaliar** [comment]
Sir, I would like to contribute in c++

**Comment by vijaylaxmi26** [comment]
Can i try to work on this issue? I would like to contribute in c++

**Comment by SaloniK17** [comment]
can you please assign to me  for c?
Thank You

**Comment by pratik-choudhari** [comment]
@vijaylaxmi26 @SaloniK17 it's already assigned in C/C++.

**Comment by vijaylaxmi26** [comment]
can i try with java?
