### ISSUE TITLE
Remove large spaces between string.

### ISSUE THREAD

**Issue by ShivamYadav-Coding** [pratik-choudhari/AlgoCode#149]
# Feature ✅

## Description
Given a string of words with lots of spaces between the words , remove all the unnecessary spaces.

## Example
input:  I______live_____on_____earth
               
// Underscore( _ ) here are actually white spaces i used underscore to reprensent white space because Github is also omitting    
// the extra spaces between the input string mentioned above ;) Just seen real world example of this question while writing it.

output: I live on earth

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by VamsiMudaliar** [comment]
I would like to Code this in C++ too..

**Comment by shivangigoel1302** [comment]
Can you assign me this . I can code it in C++

**Comment by pratik-choudhari** [comment]
@shivangigoel1302 want to try other language?

**Comment by sushant19-99** [comment]
I would like to work on this task using Java , kindly assign the task.

**Comment by c0d1ng-Devta** [comment]
@pratik-choudhari can you please assign this to me in python.

**Comment by SaloniK17** [comment]
hii,can you please assign to me for c?
Thank you

**Comment by pratik-choudhari** [comment]
@SaloniK17 You have been assigned to 2 issues which is the contribution limit for this repository.
