### ISSUE TITLE
Compress the string

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#166]
# Feature ✅

## Description
Compress the elements of a string by calculating number of repetitions for every character

## Example
Input: 1222311
Output: (1, 1) (3, 2) (1, 3) (2, 1)

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by waridrox** [comment]
Would love to contribute towards the solution in C++ language !

**Comment by kishanpatel22** [comment]
Hey can I work on this issue can you assign it to me ? I would love to contribute.

**Comment by Nikhil-1503** [comment]
I would like to solve this in c++.

**Comment by pratik-choudhari** [comment]
@kishanpatel22 Language?

**Comment by Ace117MC** [comment]
can i code in python

**Comment by kishanpatel22** [comment]
@pratik-choudhari I would code in python

**Comment by paraggoyal28** [comment]
@pratik-choudhari can I do above problem in java.

**Comment by pratik-choudhari** [comment]
@paraggoyal28 Would you prefer this problem over timer in gui?

**Comment by paraggoyal28** [comment]
@pratik-choudhari  I would prefer timer gui. Assign this to someone else.
