### ISSUE TITLE
Word game

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#167]
# Feature ✅

## Description
For each input word find its occurrence.

## Example
First line is number of test cases.
In output first print number of distinct words followed by word occurrence.
Input: 
4
bcdef
abcdefg
bcde
bcdef

Output:
3
2 1 1

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Ace117MC** [comment]
can i do this in c++ ?

**Comment by vanya-24** [comment]
Please assign this to me! @pratik-choudhari

**Comment by shubha028** [comment]
Can I do in java as a part of hactoberfest?

**Comment by VamsiMudaliar** [comment]
I'd like to do this in C++ too. @pratik-choudhari

**Comment by nikhil05-code** [comment]
I would like to do in python. Please assign it to me.

**Comment by pratik-choudhari** [comment]
@vanya-24 Language?

**Comment by vanya-24** [comment]
I can do in C++,C,Python! @pratik-choudhari

**Comment by pratik-choudhari** [comment]
@vanya-24 c++
@shubha028 java
@nikhil05-code python
