### ISSUE TITLE
Infix to postfix conversion

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#175]
# Feature ✅

## Description
Conversion input infix equation to postfix expression

## Example
Input: (a / b + c) - ( d + e * f)

Output:
Original: (a / b + c) - ( d + e * f)
Postfix:  -+/abc+d*ef 

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by aayushi02agarwal** [comment]
I wanna do it in cpp. Please assign it to me.

**Comment by vaishnavirshah** [comment]
I want do this in CPP as well, please assign it to me.

**Comment by sushant19-99** [comment]
I would like to do this task using Java , kindly assign the task.

**Comment by pratik-choudhari** [comment]
@sushant19-99 You are already assigned for 2 issues which is the max limit for this repository.

**Comment by ItIsUday** [comment]
Can you please assign it to me, I would like to do it in C.

**Comment by pratik-choudhari** [comment]
@ItIsUday C/C++ has been submitted for this issue. Give a try to Python or Java

**Comment by ItIsUday** [comment]
> @ItIsUday C/C++ has been submitted for this issue. Give a try to Python or Java

I'll do it in python, you can assign it to me
