### ISSUE TITLE
Min. triangle height

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#176]
# Feature ✅

## Description
Given base b and a of a triangle as integers, find minimum integer height 

## Example
Input format -> base followed by area
Input: 17 100
Output: 12 

Input: 2 2
Output: 2 

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by akhilakonam** [comment]
Hi pratik, can I solve this in C++?

**Comment by c0d1ng-Devta** [comment]
Hi Pratik, I had solved this question in python. Is my code correct?

**Comment by VamsiMudaliar** [comment]
I would like to do this in javascript

**Comment by akhilakonam** [comment]
Hi pratik, can you please accept my PR 👍

**Comment by c0d1ng-Devta** [comment]
Yes, please mine also.

**Comment by MAHIMA01** [comment]
Hi, can you assign me this issue for Java please?
