### ISSUE TITLE
Charlie's Prime factors 

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#178]
# Feature ✅

## Description
For a given number n, find the maximum number of distinct prime factors for numbers in range [1,n]

## Example
Input: 100
Output: 3
Explanation: 30, 42 has 3 prime factors, no other number has more than 3 distinct prime factors in range [1, 100]

__Contributors are supposed to mention their coding language while asking for assignment__
__Charlie's doesn't mean anything, it's just to make the name of problem concise🤫__

**Comment by VamsiMudaliar** [comment]
Sir, I would love to contribute to this in C++

**Comment by shubhamnag14** [comment]
could you please assign me this issue?? i would like to do the tasķ

**Comment by sushant19-99** [comment]
Kindly assign it to me , I would like do the task in Java.

**Comment by sushant19-99** [comment]
@pratik-choudhari  kindly add **‘hacktoberfest-accepted’** label to the pull request once they are merged. According to the guidelines only then the requests will be considered valid for hacktober fest

**Comment by pratik-choudhari** [comment]
@sushant19-99 If you look at it again closely having hactoberfest labelled repository and a merged PR are also accepted. There is OR in between condition s.

**Comment by sushant19-99** [comment]
@pratik-choudhari Ohh okay. You are right. Thanks for clearing that out.
