### ISSUE TITLE
Is in fibonacci?

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#179]
# Feature ✅

## Description
Given integer  n, find if it is a part of fibonacci series.

## Example
Input: 3 #no of test cases
5
7
8

Output:
True
False
True

__⚠Expect number to go in thousands__
__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by VamsiMudaliar** [comment]
@pratik-choudhari  Please assign this to me i would like to code in C++

**Comment by ryanvarghese** [comment]
Hey @pratik-choudhari , I would love to work on this. Please assign this to me. I'll be using Python.

**Comment by DiSousaDev** [comment]
Please assign this to me i would like to code in Java

**Comment by pratik-choudhari** [comment]
@VamsiMudaliar you are already assigned to 2 issues which is max limit for a contributor.

**Comment by pratik-choudhari** [comment]
@ryanvarghese python and @DiSousaDev java, you are up for respective languages.

**Comment by ryanvarghese** [comment]
> @ryanvarghese python and @DiSousaDev java, you are up for respective languages. 

Okay will do it

**Comment by TheYM** [comment]
@pratik-choudhari I would like to go for this issue with C++

**Comment by SHIVANI0708** [comment]
i would like to code it in python. please allow me to do this assignment.

**Comment by SHIVANI0708** [comment]
please assign it to me I would like to code in python

**Comment by sushant19-99** [comment]
Kindly allow me to do this assignment, I will be coding in C.

**Comment by pratik-choudhari** [comment]
@sushant19-99 It has already been assigned to @TheYM
