### ISSUE TITLE
Inplace rotate square matrix by 90 degrees

### ISSUE THREAD

**Issue by ShivamYadav-Coding** [pratik-choudhari/AlgoCode#191]
# Feature ✅

## Description
Given a square matrix, turn it by 90 degrees in anti-clockwise direction without using any extra space.

## Example

Input:
Matrix:
 1  2  3
 4  5  6
 7  8  9
Output:
 3  6  9 
 2  5  8 
 1  4  7 
The given matrix is rotated by 90 degree 
in anti-clockwise direction.

Input:
 1  2  3  4 
 5  6  7  8 
 9 10 11 12 
13 14 15 16 
Output:
 4  8 12 16 
 3  7 11 15 
 2  6 10 14 
 1  5  9 13
The given matrix is rotated by 90 degree 
in anti-clockwise direction.

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Palaash05** [comment]
I would like to work in this problem using python. I request you to assign it to me.

**Comment by nayanika0208** [comment]
Hi , i can solve the problem in c++,Can you assign it to me??

**Comment by nayanika0208** [comment]
#205 
Please check my PR

**Comment by SusnatoPrime007** [comment]
I would like to work on this in java,can you assign this to me please?

**Comment by SusnatoPrime007** [comment]
I have submitted my PR for this in java section,kindly check
