### ISSUE TITLE
File Organizer Script

### ISSUE THREAD

**Issue by Skr-suyash** [pratik-choudhari/AlgoCode#194]
# Feature ✅

## Description
Create a File Organizer Script in Python which when run in a folder will take its various files like txt, xlxs, mp3, jpeg into various folders like Documents, Images, Videos, Music, Executables etc. and ignore rest of the folders. This can be achieved using Python's os module 

## Example
.txt, .xlxs, .docx will be moved to Documents Directory (create this directory). .jpg, .jpeg, .png will go to images, .exe will go to executabes etc. and rest folders will be ignored.

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by sgavil** [comment]
Hello!, I would like to contribute to this issue using Pyuthon.
