### ISSUE TITLE
SQLite interaction

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#197]
# Feature ✅

## Description
Write a program to perform simple database queries of create, select, insert, delete, show tables and update on a sqlite database only

## Example
user will type queries as input similar to a sqlite query. Output must be printed immediately with proper formatting.
Input: SELECT * FROM EMP #to be executed only after creating a db and table.

Output: Must print the tuples.

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Naziya-Parveen** [comment]
Please assign me this problem.

**Comment by pratik-choudhari** [comment]
@Naziya-Parveen The language?

**Comment by Naziya-Parveen** [comment]
@pratik-choudhari python

**Comment by ByGreez** [comment]
Hi! I will write on Golang.
