### ISSUE TITLE
Regenerate array with closest sum

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#2]
# Feature ✅

## Find minimum value to be assigned to the elements so that sum becomes greater than initial sum.

Input: 4 2 1 10 6

Output: 5

Sum of original array = 4+2+1+10+6 = 23
Sum of modified array = 5+5+5+5+5 = 25
__Mention programming language while requesting assignment__

**Comment by Raksha25** [comment]
Hi @pratik-choudhari  , I can handle this one.

**Comment by pratik-choudhari** [comment]
@Raksha25 Great let me know the language.

**Comment by Raksha25** [comment]
> @Raksha25 Great let me know the language.

Java

**Comment by m-code12** [comment]
@pratik-choudhari 
I would like to take this up in C++.

**Comment by 2tanayk** [comment]
hey @pratik-choudhari  can I take this one in C?
