### ISSUE TITLE
Number sorting with a twist

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#20]
# Feature ✅

## Description
The task is to sort n numbers in ascending format based on following conditions:
1. i<sup>th</sup> number can be exchanged only with i-1<sup>th</sup> position number.
2. Complete operation can be performed in (n(n-1)/2 -1) exchanges.
If both conditions are met print "YES" else print "NO"  

## Example
Input: 9 7 1 12 8
Output: YES

Input: 2 1
Output: NO

**Comment by Utkarshn10** [comment]
@pratik-choudhari I would like to contribute. I will be using java.
