### ISSUE TITLE
Rock Paper Scissor Game

### ISSUE THREAD

**Issue by Xenoare** [pratik-choudhari/AlgoCode#203]
Rock Paper and Scissor
This is a simple Rock, Paper and Scissor game

Description
Choose between Rock, Paper or Scissor and computer will pick a random number between 0-1 that contains Rock, Paper or Scissors

Note : All Compleated

All files must be kept in a directory.
Directory name must resemble the issue assigned.
Based on the language used, create a directory inside the language directory.
Example: If I am writing in Python I will create a directory inside Python directory.
In case a project is being contributed make sure to add the files inside a directory(name according to project) which in turn -
must be placed inside the Projects directory.
Changes done by you will not affect existing structure of the project.
Add a README.md with your name and link to github profile using your-name
Add your-name in CONTRIBUTORS.md
Note: I'm still newer in open source world, if i have anything wrong , please contact me thanks :)

**Comment by seniorglez** [comment]
Hey! I will love to develop this on Java

**Comment by Xenoare** [comment]
Oh thanks for visiting, sure u can, it will be a pleasure to use my code on Java :)

**Comment by pratik-choudhari** [comment]
@seniorglez Would you like to use another language?

**Comment by seniorglez** [comment]
@pratik-choudhari I already have this developed but I can write it in another language... In which language will you like to have it?

**Comment by pratik-choudhari** [comment]
@seniorglez Anyone from Go, python, c, c++

**Comment by seniorglez** [comment]
I will go also with python and js then ;)

**Comment by DishantIsrani** [comment]
I can try this in python

**Comment by pratik-choudhari** [comment]
@DishantIsrani It is already assigned to someone else in python
