### ISSUE TITLE
Lucky Number 

### ISSUE THREAD

**Issue by Naziya-Parveen** [pratik-choudhari/AlgoCode#207]
Problem Statement: 
Lucky numbers are subset of integers. 
Take the set of integers
1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,……

First, delete every second number, we get following reduced set.
1,3,5,7,9,11,13,15,17,19,…………

Now, delete every third number, we get
1, 3, 7, 9, 13, 15, 19,….….

Continue this process indefinitely……
Any number that does NOT get deleted due to above process is called “lucky”.

Therefore, set of lucky numbers is 1, 3, 7, 13,………

__Mention language in comments for assignment__

**Comment by Naziya-Parveen** [comment]
I would like to contribute to this problem in Golang.

**Comment by CodeBuster598** [comment]
I would love to code it in C++. Can you assign it to me.

**Comment by SusnatoPrime007** [comment]
I'd like to do it in Java,please assign me to this.

**Comment by mbhole1857** [comment]
Hi Nazriya, can you please assign me this issue. and let me know which language would you prefer?

**Comment by PriyanshTri** [comment]
I want to do this in Python

**Comment by PriyanshTri** [comment]
#253 @pratik-choudhari please refer to this PR. Thanks
