### ISSUE TITLE
Path Count in a Binary Matrix - DP

### ISSUE THREAD

**Issue by Ankitcode99** [pratik-choudhari/AlgoCode#208]
# Feature ✅

## Description
Find number of possible paths from the top left cell of a matrix to the bottom-most right cell in a binary matrix.

## Example
Consider the following binary matrix where, 0 indicates the path is blocked and 1 indicates the path is open

**Input**
```
1 1 1 1
1 1 0 1
0 1 0 1
1 1 1 1
```

**Output** - 4
## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__I want to contribute in C++__

**Comment by nayanika0208** [comment]
Can i contribute in python??

**Comment by Ankitcode99** [comment]
@pratik-choudhari the issue is yet to be assigned to me.

**Comment by nayanika0208** [comment]
Hey i have already contributed twice to the repo ,so as per rules i can't do more,So please assign this one to other people.Thanks

**Comment by pratik-choudhari** [comment]
Oh Thanks for bringing that up @nayanika0208
