### ISSUE TITLE
Applying KMP algorithm

### ISSUE THREAD

**Issue by CodeBuster598** [pratik-choudhari/AlgoCode#210]
# Feature ✅

## Description
Given two strings, pattern and text, find the number of occurrences of pattern in text.

## Example
Input :
abc
abcdabc

Output :
2

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by CodeBuster598** [comment]
I would like to do this in C++. Please assign it to me.

**Comment by nayanika0208** [comment]
Can i contribute in python?
