### ISSUE TITLE
Print matrix in spiral format.

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#22]
# Feature ✅

## Description
Print the matrix input in a spiral format

## Example
Input:
1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16

Output:
1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10

__Mention language while requesting for assignment__

**Comment by therealansh** [comment]
Hey @pratik-choudhari can i work on this one?  I will be using C++. Thanks.

**Comment by ManuGupta9780** [comment]
Hey @pratik-choudhari  can I work on this Problem? My programming language is C++. Thank You

**Comment by pratik-choudhari** [comment]
Hey @ManuGupta9780 This issue has already been assigned to @therealansh , maybe you could try some other language or other problem overall.

**Comment by ManuGupta9780** [comment]
@pratik-choudhari can work on Java for this problem?

**Comment by pratik-choudhari** [comment]
@ManuGupta9780 yup, no problem!

**Comment by atharvakarnik** [comment]
Hey @pratik-choudhari, I have done this problem earlier in Python. Can you assign it to me?
