### ISSUE TITLE
Sort traingles

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#227]
# Feature ✅

## Description
Given all sides, calculate the triangle area and print the sides in ascending order of their areas.

## Example
First line will be the number of test cases.
Input:
3
7 24 25
5 12 13
3 4 5

Output:
3 4 5
5 12 13
7 24 25

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Teleri** [comment]
Hello - I'll try this one in Javascript 👍

**Comment by Kirkkm** [comment]
Hello, I would like to try this on in python, Thanks!

**Comment by cianopiano** [comment]
Hi, I'd love to try this in C, if possible.

**Comment by titanabrian** [comment]
Hi, I would like to try on golang

**Comment by PriyanshTri** [comment]
I want to do this in python

**Comment by pratik-choudhari** [comment]
@PriyanshTri This issue has been already assigned in python. Check the labels for languages assigned.
