### ISSUE TITLE
Number frequency

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#228]
# Feature ✅

## Description
Given a string find the frequency of single digits(0-9) in it.

## Example
Input: 
a11472o5t6

Output:
0 2 1 0 1 1 1 1 0 0 

Explanation:
1 occurs twice
2,4,5,6,7 occur once
rest don't occur at all

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by falguni-k** [comment]
Hi, I can do it in c++. Can you please assign it to me?

**Comment by TediaN97** [comment]
Hello, i would like if u assign me on this issue. I will do in Python.

**Comment by Kirkkm** [comment]
Hello, I would like to be assigned this issue. I would us python to develop this. Thanks!

**Comment by ItIsUday** [comment]
Hey, I'd like to implement it using python if assigned

**Comment by JahshakaDEV** [comment]
Hey, I would like to do it in Java. Can you please assign it to me?

**Comment by deepharshsri** [comment]
Hey can  i work on this using java.

**Comment by pratik-choudhari** [comment]
@falguni-k @TediaN97 @deepharshsri Are assigned according to FCFS.

**Comment by pratik-choudhari** [comment]
@Kirkkm @ItIsUday Y'all can try javascript and golang

**Comment by deepharshsri** [comment]
how to save file like freuency.java in the java folder will be ok ?

**Comment by pratik-choudhari** [comment]
Create a folder inside `Java` , named after the problem and place the .java file inside it along with a readme containing your name and github link.

**Comment by RyanPapazoglou** [comment]
Hey can you assign this to me? I'll do it with JavaScript

**Comment by deepharshsri** [comment]
Hey, can you assign me? I want to contribute with javascript?

**Comment by Bhairavi-shah** [comment]
> @Kirkkm @ItIsUday Y'all can try javascript and golang

I would like to try this in golang. Please assign this to me. Thanks!
