### ISSUE TITLE
Internet speed test

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#23]
# Feature ✅

## Description
Create a program to calculate Internet speed.

## Example
Output Upload and Download speeds

__Mention language when requesting assignment__

**Comment by sparsh9** [comment]
I would like to handle this issue. I can make one using Python.

**Comment by amitsat27** [comment]
i can program it with some gui in python

**Comment by albertbolt1** [comment]
I can do it using django like a webapp

**Comment by pratik-choudhari** [comment]
@albertbolt1 Sure! Place it under `Projects` directory

**Comment by amitsat27** [comment]
@pratik-choudhari Please use "hacktoberfest" label to participate instead of "Hacktoberfest" it is written on profile page
