### ISSUE TITLE
Timer with GUI⏳

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#233]
# Feature ✅

## Description
task is to create a timer application with GUI, it should include start, pause, lap and reset button. Must display time in milliseconds precision.
Website can also be created by using only html, css and javascript(framework of choice).

## Example
User must be able to react in real-time.

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by kshitijshah95** [comment]
@pratik-choudhari I'd like to contribute on this particular feature. 
I will be using the following technologies for the same: HTML, CSS, Vanilla JS

p.s: I am new to Open Source Contributions and this is will be my first contribution

**Comment by pratik-choudhari** [comment]
Welcome to open source @kshitijshah95 🎉. Yes you can start working on the issue. Remember to follow the code of conduct. All the steps for contributing are mentioned in the readme of repository.

**Comment by paraggoyal28** [comment]
Hello pratik-choudhari can you assign this task to me. And is there any specific UI for this task or I can choose by myself.

**Comment by paraggoyal28** [comment]
Hello @pratik-choudhari  I would like to work on this task. Please assign it to me. Further more is there any specific ui for this or we can choose on our own.

**Comment by pratik-choudhari** [comment]
@paraggoyal28 What is going to be your tech stack?

**Comment by paraggoyal28** [comment]
@pratik-choudhari  I will use React

**Comment by pratik-choudhari** [comment]
@paraggoyal28 include `using_react` in your folder name.

**Comment by xyther14** [comment]
I would love to work on this using Flutter.
