### ISSUE TITLE
Website to PDF📑

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#234]
# Feature ✅

## Description
A script to save a website page as PDF, URL will be provided by user.

## Example
The PDF must be encoded appropriately and renamed to the domain name of website.

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by RyanPapazoglou** [comment]
Hey, can I do this with python?

**Comment by rashi-s17** [comment]
Hey, I will like to work on this using electronjs. Can you assign it to me?
