### ISSUE TITLE
Doubly linked list in C/C++⛓

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#235]
# Feature ✅

## Description
Implement a doubly linked list with the ability of inserting, deleting, updating and searching an element.

## Example
Entire flow must be menu-driven. Menu includes insert, delete, update, search and display elements from left to right.

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by burko265** [comment]
Can i work on this Issue ?

**Comment by burko265** [comment]
Can you assign this to me?

**Comment by Itachi8374** [comment]
I would love to try this @pratik-choudhari

**Comment by SaloniK17** [comment]
Hi, can you please assign me this issue in c language?
Thank you.

**Comment by AnkitaM84** [comment]
Hey! can you assign this to me in Java? 
Thank you

**Comment by AnkitaM84** [comment]
Hey! Can you please assign this to me in C++ ?
Thank you

**Comment by rishika-singh49** [comment]
I  would like to work on this.....
will you please assign me this issue in c language?

**Comment by sid-1207** [comment]
Is it still open
I want to contribute in C

**Comment by burko265** [comment]
Yes ofcourse, i work on it.

Dňa ut, 13. okt 2020, 14:31 Siddharth Shah <notifications@github.com>
napísal(a):

**Comment by sid-1207** [comment]
> @sid-1207 Language?

C or C++ whichever

**Comment by pratik-choudhari** [comment]
@sid-1207 They are not distinguished.

**Comment by sid-1207** [comment]
> @sid-1207 They are not distinguished.

Should I?

**Comment by raj2729** [comment]
Hi @pratik-choudhari I would like to work on this in C/C++ , could you please assign it to me

**Comment by pratik-choudhari** [comment]
@sid-1207 @raj2729 None can be assgined in C or C++ it is assgned to @rishika-singh49
