### ISSUE TITLE
Random quote scrape and display💡

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#236]
# Feature ✅

## Description
Write a script to display random quote, preferably after scraping them from `http://quotes.toscrape.com/`  and storing them as JSON

## Example
Program must display a quote if user inputs 1 else it must end if user inputs -1.

__It will be great if it includes GUI or website⚡⚡__
__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by bottleInALightning** [comment]
I will try to solve this challenge in **Python** with django as a web-application

**Comment by pratik-choudhari** [comment]
@bottleInALightning Use the `Projects` directory instead of `Python`

**Comment by bottleInALightning** [comment]
ok

**Comment by bottleInALightning** [comment]
I am done and have pull requested you

**Comment by rashi-s17** [comment]
Hey, I will like to work on this in JavaScript. Can you assign it to me?

**Comment by pratik-choudhari** [comment]
@rashi-s17 sure.
