### ISSUE TITLE
Zip and Unzip🤐

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#237]
# Feature ✅

## Description
Write a program to zip a folder or unzip a `.zip` file.

## Example
Location of source file to zip/unzip will be provided by user.

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by shrey27tri01** [comment]
@pratik-choudhari Can I work on this problem in Python?
Also, a command line program will suffice, right? As in, the user provides the source files through command line arguments.

**Comment by pratik-choudhari** [comment]
@shrey27tri01 yup, CLI will do.

**Comment by PriyanshTri** [comment]
can I work on this?

**Comment by pratik-choudhari** [comment]
@PriyanshTri Will you be using language other than python? because python has been already assigned.

**Comment by PriyanshTri** [comment]
python only...

**Comment by pratik-choudhari** [comment]
It's already been assigned. May be checkout another issues🧐

**Comment by shrey27tri01** [comment]
@pratik-choudhari I have created a PR [here](https://github.com/pratik-choudhari/AlgoCode/pull/269). Can you please review it? :)

**Comment by AyeshW** [comment]
Can you please assign me to work on this in Java?
