### ISSUE TITLE
Convert numbers to their word forms🔡

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#238]
# Feature ✅

## Description
Given a number create and display its word form.

## Example
Input: 6782
Output: six thousand seven hundred and eighty two

Input:  1,11,098
Output: one lakh eleven thousand and ninety eight

Upper limit: 9,99,999

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by shobhitsundriyal** [comment]
Can you assign this to me? I will be using python.

**Comment by harshitalashkari** [comment]
Can you please assign this to me? I have solution ready for this.
I will use java

**Comment by SpiderMath** [comment]
Can you assign this to me?
I am using JavaScript.

Just an Important question:
What is the Upper Limit to convert?
Crores?
Because I don't know any unit greater than that...

**Comment by SpiderMath** [comment]
My Solution is Ready...
Can you please assign this to me?

**Comment by pratik-choudhari** [comment]
@SpiderMath Lakhs is fine.

**Comment by cianopiano** [comment]
Could I be assigned for this in C please?

**Comment by ankita319** [comment]
Can you assign this to me? I will be using c language.

**Comment by pratik-choudhari** [comment]
@ankita319 It has already been assigned to someone else.
