### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by ItIsUday** [pratik-choudhari/AlgoCode#242]
# Feature ✅

## Description
Given the number of disks and labels for the towers, displays necessary moves required to solve the Tower of Hanoi problem.

## Example
Input: 2 A B C

Output:
Move Disk 1 from A to B
Move Disk 2 from A to C
Move Disk 1 from B to C
It took 3 moves in total

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__I would like to contribute in Python__

**Comment by ShivamYadav-Coding** [comment]
I would like to contribute in c++

**Comment by SAKSHI2569** [comment]
I would like to contribute in c .
will you please assign me this issue?

**Comment by pratik-choudhari** [comment]
@SAKSHI2569 It has already been assigned to shivam.

**Comment by leli-1** [comment]
Can you assign this to me in python

**Comment by sawzedong** [comment]
Hi, could I take this in Java?
