### ISSUE TITLE
Chatting client in python🐍

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#246]
# Feature ✅

## Description
Using `sockets` library in python, create a server and client script for a chatting application. All I/O will be from terminal.

## Example
Two separate python scripts will be run on two terminals. They must configure the connect and set up communication. Typing 'bye' will terminate respective script.

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Mrsterius** [comment]
Hi @pratik-choudhari, 
I can do this in Python. Can I proceed?

**Comment by pratik-choudhari** [comment]
@Mrsterius Assigned to you.

**Comment by Mrsterius** [comment]
Submitted. Please let me know if there are any changes required.
