### ISSUE TITLE
Remindabot🤖

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#248]
# Feature ✅

## Description
Write a script to remind user every 20 minutes to get up and walk or stretch a little. As you might be working on PC, you might not notice the warning on terminal. So the script must interact via notifications or Text to speech.

## Example

If user enters | the program must
-------------- | --------------------
-1 | Terminate
0 | Pause
1 | Resume

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by GoluffyxD** [comment]
Hey!I'd like to work on this! Can you assign it to me? (Language: Python)

**Comment by GoluffyxD** [comment]
Hey! Let me know if any additional features are needed! I'd appreciate any suggestions @pratik-choudhari

**Comment by pratik-choudhari** [comment]
@GoluffyxD Great work👏
