### ISSUE TITLE
EDA on Titanic Dataset

### ISSUE THREAD

**Issue by Skr-suyash** [pratik-choudhari/AlgoCode#261]
# Feature ✅

## Description
Dataset : https://www.kaggle.com/c/titanic
Do some nice EDA and Data Visualization on the Titanic Dataset in Python or R

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by pratik-choudhari** [comment]
Also refer issue #162

**Comment by PrattJena** [comment]
Hey Pratik!
I have just started github and would like to be assigned this issue.

**Comment by uddeshyatyagi** [comment]
Hey @pratik-choudhari ,would you please assign this to me?
I'm extremely willing to take this issue.
Thank you!!!

**Comment by pratik-choudhari** [comment]
@uddeshyatyagi It has been assigned to @PrattJena 
@PrattJena You are working on it right?

**Comment by PrattJena** [comment]
Since the branch is merged its best to close this issue.

**Comment by pratik-choudhari** [comment]
@PrattJena That issue is generic
