### ISSUE TITLE
BFS and DFS in C++

### ISSUE THREAD

**Issue by cs-mshah** [pratik-choudhari/AlgoCode#263]
# Feature ✅
## Checklist:

- [✅ ] I have read the project guidelines.
- [✅ ] I have checked all the existing projects, before submitting a new project issue.
- [✅ ] This issue will be meaningful for the project.
- [✅ ] I will contribute more in future

**Comment by paraggoyal28** [comment]
@cs-mshah  please assign this task to me.

**Comment by cs-mshah** [comment]
Hey man, This should be assigned to me. That's the reason to open the issue. According to your rules, if you want to contribute you should open an issue.

**Comment by pratik-choudhari** [comment]
Yep you should create if you want to contribute to it. But just creating doesn't suffice you have to mention i want to do this in ... language either in the issue or the comment.
