### ISSUE TITLE
Number System Conversion

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#264]
# Feature ✅

## Description

A menu-driven code to convert a given number from one base system to another
Menu:
1. Binary to Decimal
2. Binary to Octal
3. Binary to Hexadecimal
4. Decimal to Binary
5. Decimal to Octal
6. Decimal to Hexadecimal
7. Octal to Binary
8. Octal to Decimal
9. Octal to Hexadecimal
10. Hexadecimal to Binary
11. Hexadecimal to Octal
12. Hexadecimal to Decimal
13. Exit

## Example

1.Decimal to Binary      2.Decimal to Hexadecimal        3.Decimal to octal
 4.Binary to Decimal     5.Binary to Hexadecimal         6.Binary to octal
 7.Hexadecimal to Decimal        8.Hexadecimal to Binary         9.Hexadecimal to Octal
 10.Octal to Decimal     11.Octal to Binary      12.Octal to Hexadecimal
 13.Exit

Enter your choice:
7
Enter a Hexadecimal number:
A
Decimal number is:10

1.Decimal to Binary      2.Decimal to Hexadecimal        3.Decimal to octal
 4.Binary to Decimal     5.Binary to Hexadecimal         6.Binary to octal
 7.Hexadecimal to Decimal        8.Hexadecimal to Binary         9.Hexadecimal to Octal
 10.Octal to Decimal     11.Octal to Binary      12.Octal to Hexadecimal
 13.Exit

Enter your choice:
13
## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by pallavivaswani** [comment]
I'd like to contribute in Java

**Comment by SaloniK17** [comment]
can you please assign to me for c?
Thank you

**Comment by nehalgupta8501** [comment]
I would like to contribute in C++, thanks!

**Comment by pratik-choudhari** [comment]
@nehalgupta8501 It has been assigned in c/c++, you can try another issue.

**Comment by Bhavya-Tripathi** [comment]
I could do this in python. Could you assign it to me?

**Comment by itayz1230** [comment]
Hi, my FIRST real issue, so I guess I have to ask you to assign it to me and then I can start working on it?
I would like to solve it with python or C#, thanks!

**Comment by pratik-choudhari** [comment]
@itayz1230 Assigned for c#.

**Comment by ieternalleo** [comment]
I would to contribute in GoLang.
