### ISSUE TITLE
Graph Traversal (BFS/DFS)

### ISSUE THREAD

**Issue by sauravUppoor** [pratik-choudhari/AlgoCode#27]
# Feature ✅

## Description

You are given an undirected unweighted graph in the form of an adjacency list ([Resource on adjacency list](https://www.hackerearth.com/practice/algorithms/graphs/graph-representation/tutorial/)). Given a starting and ending node number you have to output the number of nodes in the shortest path between the starting and ending node(excluding starting and ending nodes). Refer to examples for better understanding.

**Input format -** 
N M
u1 v1
u2 v2
...
uM vM
A B

Here, N is the number of nodes and M is the number of edges. M lines follow where the ui vi represents and edge between node ui and vi. A and B are the starting and ending node respectively. Nodes are numbered from 1 to N.

## Example

**Input -**
4 4
1 2
2 3
2 4
3 4
1 4

**Output -**
1

**Explanation -**
The shortest path between 1 and 4 is 1 --> 2 --> 4. Thus there is just 1 node between A and B.

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

**Comment by SakshiUppoor** [comment]
I'd like to work on this issue using C++ @pratik-choudhari

**Comment by pawki07** [comment]
Hey, I would like to work on this issue. Please assign it to me.

**Comment by pratik-choudhari** [comment]
@pawki07 Mention the language as it is written in the issue.

**Comment by pawki07** [comment]
@pratik-choudhari I will use C++ language.

**Comment by jyotiGambhir** [comment]
Can you assign this issue to me? I would like to code it in CPP

**Comment by pratik-choudhari** [comment]
@jyotiGambhir It has been already assigned for in CPP language, you can take up a different language.

**Comment by jyotiGambhir** [comment]
> @jyotiGambhir It has been already assigned for in CPP language, you can take up a different language.

ok I can code it in Python then
