### ISSUE TITLE
Find 'n'th node from the end of a linked list

### ISSUE THREAD

**Issue by ShivamYadav-Coding** [pratik-choudhari/AlgoCode#271]
# Feature ✅

## Description
Given a linked list, find 'n'th node from the end for a given value of n (n > 0).

## Example
For example, for the following linked list
![image](https://user-images.githubusercontent.com/59358990/95671350-944c1e00-0bb3-11eb-991c-01a4c21ebe76.png)

if n = 2, we have to find 2nd node from the end which is node 6.
if n = 1, we have to find 1st node from the end which is node 7.

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by dhruvin5** [comment]
can you assign this to me in c++?

**Comment by marlonluca** [comment]
Can I also work on it, using java?

**Comment by almas-ashruff** [comment]
Can I solve using C++? Thank you.

**Comment by dhairya-parikh** [comment]
Can I solve it in JAVA? 
Thank you.

**Comment by pratik-choudhari** [comment]
@almas-ashruff @dhairya-parikh They are already assigned, choose another issue.

**Comment by Shreejichandra** [comment]
Can I solve it in Python?
Thank you.
