### ISSUE TITLE
Count single digits

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#273]
# Feature ✅

## Description
For a given number find out the count of digits appearing exactly once

## Example
Input: 99995844
Output: 2(only 5 and 8 appear once)

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by jayaganeshkumar** [comment]
@pratik-choudhari  Can you assign me this? I want to work on it in Python.

**Comment by deril2605** [comment]
Interested, python

**Comment by vaishnavirshah** [comment]
Can you assign this to me? I would like to work on it in CPP

**Comment by anil-goudar** [comment]
I wanna work in JS. Assign the issue please.

**Comment by jayaganeshkumar** [comment]
@moderators

**Comment by almas-ashruff** [comment]
Can I work on this using C++? Kindly assign. Thank you

**Comment by pratik-choudhari** [comment]
@almas-ashruff It already been assigned for c/c++.

**Comment by alvinuday** [comment]
Hi really interested in this problem, could assign me this ,i will be coding in python

**Comment by pratik-choudhari** [comment]
@alvinuday It is already been assigned in python.

**Comment by jayaganeshkumar** [comment]
@pratik-choudhari  I made a PR. Check it and merge

**Comment by alvinuday** [comment]
can you please assign numero perfecto to me , python

**Comment by dhairya-parikh** [comment]
Can you please assign it to me, for JAVA?
Thank you.

**Comment by jainsarthak216** [comment]
Can I do Single digit count issue in python?

**Comment by ke3peR007** [comment]
please let me know if I can work on these using python

**Comment by pratik-choudhari** [comment]
@ke3peR007 Nope, It has already been assigned.

**Comment by huseyinsimsekk** [comment]
Can you please assign it to me, for C#?
Thank you.

**Comment by bhavya092** [comment]
Can you assign this to me (C++)?
