### ISSUE TITLE
Find if a number is automorphic

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#274]
# Feature ✅

## Description
Given a number, find out if the number is automorphic.
An automorphic number is a number whose square ends with the same digits as the number itself.

## Example
Input: 25
Output: Yes

## Explanation
 square of 25 = 625 and it ends with the number 25

## Checklist:

- [ ] I have read the project guidelines.
- [ ] I have checked all the existing projects, before submitting a new project issue.
- [ ] This issue will be meaningful for the project.
- [ ] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Harshalszz** [comment]
Hey! can I work on this in C++.

**Comment by pratik-choudhari** [comment]
@Harshalszz Sure, assigned to you in C++

**Comment by anil-goudar** [comment]
Wanna implement in Python, please assign to me.

**Comment by anil-goudar** [comment]
@pratik-choudhari Added the solution and please review.

**Comment by Isha2208** [comment]
Hey @pratik-choudhari , can you assign the issue to me. I want to implement it using C

**Comment by pratik-choudhari** [comment]
Hi @Isha2208 It has been assigned for in c/c++

**Comment by sarthak-21** [comment]
Hey! @pratik-choudhari can I work on this in java?
