### ISSUE TITLE
Floyd's triangle

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#275]
# Feature ✅

## Description
Floyd’s triangle, named after Robert Floyd, is a right-angled triangle that is made up using natural numbers. It starts from 1 and consecutively selects the next greater number in the sequence. Given number of rows program should print a valid triangle.

## Example
Input: 5
Output:                                                                                                    
1                                                                                                                          
2 3                                                                                                                        
4 5 6                                                                                                                      
7 8 9 10                                                                                                                   
11 12 13 14 15

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by argha-dot** [comment]
@pratik-choudhari can you assign me this? I can code in python

**Comment by almas-ashruff** [comment]
Can you assign this to me in C++?

**Comment by alvinuday** [comment]
Hi, i would like to code this program in Java, can you please assign it to me

**Comment by pratik-choudhari** [comment]
@alvinuday It has been assigned to @argha-dot for python.

**Comment by rileyhgrant** [comment]
Hey @pratik-choudhari, may I be assigned this for Java?

**Comment by raj2729** [comment]
Hi @pratik-choudhari  i would like to code this program in Python, can you please assign it to me ?

**Comment by pratik-choudhari** [comment]
@raj2729 Sorry it has been assigned in python to @argha-dot

**Comment by raj2729** [comment]
> @raj2729 Sorry it has been assigned in python to @argha-dot

Okay no problem , thank you

**Comment by bgbenzer** [comment]
Hi, Can I try this with C#
