### ISSUE TITLE
Pascal's triangle

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#276]
# Feature ✅

## Description
Each number in the row is the sum of the left number and right number on the above row. if a number is missing in the above row, it is assumed to be 0. the first row starts with number 1.  Given number of rows print a valid triangle.

## Example
Input: 5
Output:
     1
    1 1
   1 2 1
  1 3 3 1
1 4 6 4 1

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by ddaniss** [comment]
Can I get this one?

**Comment by omarahmed1111** [comment]
Can you assign me this ? (c++)

**Comment by NandiniMundra-8** [comment]
hey @pratik-choudhari ,can you assign this to me ,I would be performing it in c language?

**Comment by alvinuday** [comment]
Hi , i am interested in coding a solution for this problem in python , can you please assign this to me

**Comment by pratik-choudhari** [comment]
@NandiniMundra-8 It has been assigned to @omarahmed1111 based on FCFS.

**Comment by subhadeep1912** [comment]
Hey @pratik-choudhari i can try this in C#, Can you assign me? Thank you

**Comment by pratik-choudhari** [comment]
@subhadeep1912 You cant PR for this issue. You have already 2 contributions.

**Comment by subhadeep1912** [comment]
@pratik-choudhari I cant make more than 2 contributions?

**Comment by pratik-choudhari** [comment]
@subhadeep1912 Yep, read code of conduct.
