### ISSUE TITLE
Palindromic pyramid

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#277]
# Feature ✅

## Description
The palindromic number are the number whose reverse is equal to the original number. Given number of rows print a valid palindromic pyramid.

## Example
Input: Enter number of row:  5
Output: 
         1
       121
     12321
   1234321
123454321

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Harshalszz** [comment]
Hey! can I work on this in Python.

**Comment by AyeshW** [comment]
Hi, I can work on this in Java.

**Comment by Harshalszz** [comment]
Hey! can I work on this in C++ also.

**Comment by Isha2208** [comment]
Hey, can i work on it using C++/C

**Comment by pratik-choudhari** [comment]
@Harshalszz No you can't buddy. @Isha2208 Limit is surpassed.

**Comment by bgbenzer** [comment]
Hi, Can i try this one with C#

**Comment by anshika0207** [comment]
@pratik-choudhari can you assign this to me? I can code in c++
