### ISSUE TITLE
Mirrored rhombus

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#278]
# Feature ✅

## Description
A rhombus is a shape which has all sides congruent, opposite sides parallel and diagonals crossing at 90 degrees. Given number of rows print a valid mirrored rhombus

## Example
Input: 4
Output:
<pre>
      ****
    ****
  ****
****
</pre>

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by TheBlckCat** [comment]
Hi ✌️,
I want to work on this issuein. 
* In what language?

**Comment by almas-ashruff** [comment]
Can you assign this to me, please?  (C++)

**Comment by Monigingir** [comment]
Hi Pratik, please can this be assigned to me, i would like to use python

**Comment by TheBlckCat** [comment]
If I have to choose the language, I would like to do it in C (remember I asked for it first hahaha)

**Comment by pratik-choudhari** [comment]
@TheBlckCat Yup, assigned in C.

**Comment by almas-ashruff** [comment]
Assign in Java. Thanks.
