### ISSUE TITLE
String operations

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#279]
# Feature ✅

## Description
Given an input string, perform:
* String Length
* Count number of vowels
* Check if the string is Palindrome
* Remove Vowels from the string
* Calculate the frequency of characters in the string
* Replace substring in a string
* Remove spaces from the string
* Capitalize the first and last character of each word in the string
* Count the sum of numbers in a string
* Concatenate with another input string

## Example
Must be a menu driven program

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by ravidyarev** [comment]
@pratik-choudhari can you please assign me this issue. Will implement in Java.

**Comment by xyther14** [comment]
Can you assign me this? I can implement in Java.

**Comment by anil-goudar** [comment]
I  wanna implement using JS and Python, please assign the issue.

**Comment by NandiniMundra-8** [comment]
hey @pratik-choudhari can you assign this to me ,I would love to perform this task in c language?

**Comment by saurabh-daware** [comment]
What do you mean by menu driven program

**Comment by saurabh-daware** [comment]
What do you mean by a menu driven program?

**Comment by pratik-choudhari** [comment]
@anil-goudar You are already assigned to 2 issues.

**Comment by pratik-choudhari** [comment]
@saurabh-daware All the operations mentioned above must be displayed as a menu. User will then choose from the menu the operations to perform. Such as input 1 for string length.

**Comment by ghanender-chauhan** [comment]
assign me this issue . I will do in python

**Comment by saurabh-daware** [comment]
Can you assign me, I'll do in Golang

**Comment by dhairya-parikh** [comment]
Can you please assign it to me, for JAVA?
Thank you.

**Comment by eeayd** [comment]
hey can you assign me this? I will implement in Ruby, thanks!

**Comment by Bhairavi-shah** [comment]
Hey! I would like to implement this in Go. Please assign this to me. Thank you!

**Comment by rishika-singh49** [comment]
can i do this in c++?

**Comment by pratik-choudhari** [comment]
@rishika-singh49 I am sorry but it is already assigned.

**Comment by rishika-singh49** [comment]
so can i do this in java

**Comment by sarthak-21** [comment]
can I do this in C?

**Comment by pratik-choudhari** [comment]
@rishika-singh49 @sarthak-21 I am sorry but it is already assigned.

**Comment by pratik-choudhari** [comment]
@saurabh-daware I am sorry I did not see your assignment request. Would you be interested in any other issue?

**Comment by sarthak-21** [comment]
Can I try this in python?

**Comment by kingaj** [comment]
can you assign to me for java

**Comment by pratik-choudhari** [comment]
@sarthak-21 @kingaj  It has been already assigned in py and java

**Comment by pratik-choudhari** [comment]
@sarthak-21 See issues tab.

**Comment by saurabh-daware** [comment]
> @saurabh-daware I am sorry I did not see your assignment request. Would you be interested in any other issue?

It's fine. I would like to solve issue #328.
