### ISSUE TITLE
Can Balance?

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#280]
# Feature ✅

## Description
Given a non empty array, return true if there is a place to split the array so that the sum of the numbers on one side is equal to the sum of the numbers on the other side.

## Example
Input: 1, 1, 1, 2, 1
Output: True

Input: 2, 1, 1, 2, 1
Output: False

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by ankitsri98** [comment]
Please Assign this doubt to me . 
My Language is C++.
Thank you.

**Comment by sashpawar11** [comment]
Hey can you assign me this task!

**Comment by marlonluca** [comment]
Hey! I want to work on this, using Java :-)

**Comment by ghanender-chauhan** [comment]
i want to work on this issue . I will do in python

**Comment by Monigingir** [comment]
Hi Pratik, May I work on this. i would like to use python.

**Comment by eeayd** [comment]
hello, I already wrote the code in Python. I would love to share if you can assign me, thanks!

**Comment by dhairya-parikh** [comment]
Can you please assign it to me, for JAVA?
Thank you.

**Comment by pratik-choudhari** [comment]
@eeayd @Monigingir This issue has already been assigned to other contributors based on FCFS. 
@dhairya-parikh You have been assigned to 2 issues which is the max limit for this repository.

**Comment by eeayd** [comment]
okay then I implemented it in Ruby too. I can share that one if you assign me, thanks.

**Comment by pratik-choudhari** [comment]
@eeayd Actually we are not accepting submissions for ruby, you can solve other issue in python!

**Comment by ricardosmithco** [comment]
Hi @pratik-choudhari can you please assign this to me I can provide working Java solution (today) :)

**Comment by pratik-choudhari** [comment]
@ricardosmithco It is already assigned so I can't do that.

**Comment by ricardosmithco** [comment]
Okay, I didn't see it was already assigned for Java solution. Thanks @pratik-choudhari
