### ISSUE TITLE
Factorial of a large number

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#3]
# Feature ✅

## Description

Calculate factorial of a large number such as 100 or 200

## Example

Input: 100
Output : 933262154439441526816992388562667004-
         907159682643816214685929638952175999-
         932299156089414639761565182862536979-
         208272237582511852109168640000000000-
         00000000000000

__⚠Note: The program must not use the normal logic of n! = n*(n-1)*...__

**Comment by vedanthv** [comment]
Hi. Please can you assign the task to me.
Language: Python

**Comment by nits01** [comment]
Can you please assign it to me.
Language :  Java

**Comment by vedanthv** [comment]
@pratik-choudhari added the code in Python. Please review and merge

**Comment by codermind-divya** [comment]
Can I work on this in C++?

**Comment by pratik-choudhari** [comment]
@codermind-divya @vedanthv has already made the contribution in c++.
