### ISSUE TITLE
hackerrank problems

### ISSUE THREAD

**Issue by rijusougata13** [pratik-choudhari/AlgoCode#302]
# Feature ✅
# Bug 🐞
# Documentation 📑

## Description
INCREASE YOUR SKILL (hackerrank problem) (c++)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by pratik-choudhari** [comment]
@rijusougata13 This issue is vague and seems spammy.
