### ISSUE TITLE
Can we sort ?

### ISSUE THREAD

**Issue by PulkitPansari13** [pratik-choudhari/AlgoCode#305]
# Feature ✅

## Description

Given an array A with n integers return True if it is possible to sort the array in increasing order by swapping the i-th element A[i] with the (i+k)-th element A[i+k] else return False. You may perform the operation any number of times. 

### Input format
n k
A1 A2 A3 ......An

## Example

input :
6 1
2 4 1 3 5 8
output:
True

input:
6 2
4 2 7 1 3 6
output:
False

input:
4 2
4 7 1 3
output:
True

In sample 1, we can always swap adjacent elements and we will get sorted array 
In sample 2, no swapping will lead to a sorted array
In sample 3, we can swap 1st and 3rd element as well as 2nd and 4th element 
## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by raj2729** [comment]
Hi @pratik-choudhari , I would like to do this code in Java . Could you please assign me for the same ?

**Comment by sarthak-21** [comment]
I would like to do this code in C. May I?

**Comment by raj2729** [comment]
> Hi @pratik-choudhari , I would like to do this code in Java . Could you please assign me for the same ?

I have added the implementation for the required problem in Java and made a pull request . If any more changes are to be made , please do let me know .Thank you !

**Comment by Isha2208** [comment]
Hey, I would like to contribute in C/C++ language. Can you assign it to me

**Comment by KompuDan** [comment]
hi, can i contribute with this? i would use python

**Comment by pratik-choudhari** [comment]
@KompuDan You are assigned to 2 issues, it's the max limit for this repo.

**Comment by anshika0207** [comment]
@pratik-choudhari can you assign this to me? I can code in python3
