### ISSUE TITLE
K-Combination Generation

### ISSUE THREAD

**Issue by sauravUppoor** [pratik-choudhari/AlgoCode#31]
# Feature ✅

## Description

Given 2 numbers N and K and considering you have numbers ranging from 1 to N, print all the subsets of size K.

## Example

**Input -**
5 3

**Output -**
1 2 3
1 2 4
1 2 5
1 3 4
1 3 5
1 4 5
2 3 4
2 3 5
2 4 5
3 4 5

**Mention language while requesting for assignment**
## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

**Comment by shivam-S-bisht** [comment]
I would like to do this with python. 🙂
