### ISSUE TITLE
Deep learning pipeline for MNIST digit dataset

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#318]
# Feature ✅

## Description
Create a complete pipeline for reading data, formatting it, train model and evaluate.
Get the dataset [here](https://www.kaggle.com/scolianni/mnistasjpg?)

## Example
Submission must be in the form of well commented python script. not jupyter notebook

__Submission must be placed inside `Machine Learning` folder__

__As submission is for a python script it would be preferred to break down the pipeline into various functions, provided semantic names.__

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by dwij2212** [comment]
Hi! Could you assign this to me in python? TIA.

**Comment by rajpratyush** [comment]
hi @pratik-choudhari could you please assign me this issue

**Comment by pratik-choudhari** [comment]
@rajpratyush language?

**Comment by rajpratyush** [comment]
Python

**Comment by pratik-choudhari** [comment]
@rajpratyush Its assigned to @dwij2212

**Comment by dwij2212** [comment]
@pratik-choudhari I think this issue can be closed by referring to PR #378 .
