### ISSUE TITLE
Prefix and Suffix Sums

### ISSUE THREAD

**Issue by sauravUppoor** [pratik-choudhari/AlgoCode#32]
# Feature ✅

## Description

Given an array of numbers, you have to print the prefix and suffix sums of the array.

## Example

**Input -**
6
1 2 3 4 5 6

**Output -**
Prefix - 1 3 6 10 15 21
Suffix - 21 20 18 15 11 6

**Mention language while requesting for assignment**
## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

**Comment by devangmukherjee** [comment]
Can I be assigned this? I can do it using C++

**Comment by devangmukherjee** [comment]
@pratik-choudhari

**Comment by devangmukherjee** [comment]
I would like to work on this issue using C++  @pratik-choudhari

**Comment by tejaswini22199** [comment]
Hey @pratik-choudhari  if this is still open can i code in c++
