### ISSUE TITLE
Implementing the Dijkstra's algorithm

### ISSUE THREAD

**Issue by cs-mshah** [pratik-choudhari/AlgoCode#321]
# Feature ✅

## Description

Implementation of the Dijkstra's algorithm.

## Checklist:

- [✅ ] I have read the project guidelines.
- [✅] I have checked all the existing projects, before submitting a new project issue.
- [✅] This issue will be meaningful for the project.
- [✅] I will contribute more in future

**Comment by cs-mshah** [comment]
Can You assign me this issue.

**Comment by sarthak-21** [comment]
Can you assign me this, I will do it in C

**Comment by pratik-choudhari** [comment]
@cs-mshah You are up for c++, @sarthak-21 it has been assigned to @cs-mshah 
C and C++ are not distinguished here.

**Comment by codeit-dotcom** [comment]
can you assign this to me? i will code in C++

**Comment by wjyeap123** [comment]
Hi, can you assign this to me? I would like to do this in Python. Thanks.

**Comment by cs-mshah** [comment]
@pratik-choudhari the PR for C++ has been done with documentation. Kindly check and accept the PR.

**Comment by prathamesh-borse** [comment]
Is this issue still open, I would like to code Dijkstra's Algorithm in Java Thanks.

**Comment by SanidhayaAgarwal** [comment]
Hello, @cs-mshah 

I'm excited to participate in Hacktoberfest and contribute to this repository. Please consider me for any relevant tasks or issues. I look forward to collaborating with the community.

Thank you!
SanidhayaAgarwal

**Comment by cs-mshah** [comment]
Hi @SanidhayaAgarwal,
You can have a look at open issues and ask Pratik.
