### ISSUE TITLE
Max Array Sum

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#327]
# Feature ✅

## Description

Given an array of integers, find the subset of non-adjacent elements with the maximum sum. Calculate the sum of that subset.
For example, given an array [-2,1,3,-4,5]  we have the following possible subsets:
| Subset | Sum |
| --- | --- |
| [-2, 3, 5] | 6 |
| [-2, 3] | 1 |
| [-2, -4] | -6 |
| [-2, 5]        | 3|
| [1, -4]  |     -3 |
| [1, 5]      |    6 |
| [3, 5]  |        8 |

Our maximum subset-sum is 8.

##### Input Format
The first line contains an integer, n.
The second line contains n space-separated integers arr[i].
##### Output Format
Return the maximum sum described in the statement.

##### Input 
5
3 7 4 6 5
##### Output 
13
##### Explanation 
Our possible subsets are [3,4,5], [3,4], [3,6], [3,5], [7,5], [7,6] and [4,5]. The largest subset sum is  13 from subset [7,6]

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Isha2208** [comment]
Hey, **@pallavivaswani** I would like to contribute in C/C++ language

**Comment by Harshalszz** [comment]
Hey! can I work on this in C++.

**Comment by coreprogrammar** [comment]
I would like to complete this in C++
