### ISSUE TITLE
Maximum Number Of Handshakes

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#329]
# Feature ✅

## Description

The user is asked to take a number as integer n and find out the possible number of handshakes. For example, if there are n number of people in a meeting and find the possible number of handshakes made by the person who entered the room after all were settled.
##### Hint: 
nC2 calculated as n*(n-1)/2

##### Input: 
N=15

##### Output: 
Max. no. of handshakes = 105

##### Explanation: 
(15*14)/2 = 105

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by alvinuday** [comment]
Hi , i would like to code a program for this issue in python, could you please assign it to me

**Comment by therupdeep** [comment]
@pallavivaswani i would like to do this in Java. Please assign this to me.

**Comment by pratik-choudhari** [comment]
@alvinuday You are been assigned to 2 issues which is max limit for this repository.

**Comment by subhadeep1912** [comment]
hi i would love to implement the code in C#, C++ and C. Can I still work on it? If yes can you assign me, Thank you

**Comment by drashtipatel2503** [comment]
Can I code in python?
