### ISSUE TITLE
Permutations for N People to Occupy R Seats In A Classroom

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#330]
# Feature ✅

## Description

Write a code to find all the possible permutations in which N people can occupy R number of seats in a classroom
N students are looking to find R seats in a classroom. Some of the seats are already occupied and only a few can be accommodated in the classroom. The available seats are assumed as R and N number of people are looking to accommodate within the room.
##### Hint : 
nPr = n! / (n-r)!
 

##### Input:
Enter the num of people: 9
Enter the number of seats available: 5
##### Output:
Num of ways people can be seated: 15120

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by cianopiano** [comment]
I would like to do this in C please.

**Comment by therupdeep** [comment]
@pallavivaswani @pratik-choudhari i would like to do this in Java. Can you assign it to me?

**Comment by pratik-choudhari** [comment]
@therupdeep You are assigned to two issues which is max limit for this repository.

**Comment by raj2729** [comment]
Hello @pratik-choudhari I would like to do this in Java. Could you assign it to me?

**Comment by maityankan10** [comment]
I would like to do this in c++

**Comment by subhadeep1912** [comment]
@pratik-choudhari I can do this in C#

**Comment by pratik-choudhari** [comment]
@maityankan10 C/C++ is already assigned to @cianopiano

**Comment by Heisenamphetamine** [comment]
@pratik-choudhari please Assign this to me. I will do in python.
