### ISSUE TITLE
Morse Code Encoder Decoder

### ISSUE THREAD

**Issue by Sripaad** [pratik-choudhari/AlgoCode#336]
# Feature ✅

## Description
Morse code encoder and decoder

## Example
Input a message and output the morse code

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Sripaad** [comment]
@pratik-choudhari am gonna work on this.

**Comment by subhadeep1912** [comment]
Hey I can work on this issue in C, C++ or C#. Anyone of them or all of them. Can you assign me?

**Comment by barrotsteindev** [comment]
I'd like to do this in C++

**Comment by cmeyrueix4** [comment]
Hey can I get this assigned in Java?
