### ISSUE TITLE
scrape all hacktoberfest 2020 events

### ISSUE THREAD

**Issue by tusharnankani** [pratik-choudhari/AlgoCode#34]
# Feature ✅

## Description
The script should scrape all the events from the Hacktoberfest event's website and stores them in a .CSV file.
[LINK](https://hacktoberfest.digitalocean.com/events)

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] This issue will be meaningful for the project.
- [X] I will contribute more in future

**Comment by Anshul275** [comment]
I am up for this. Please assign me this task :)

**Comment by pratik-choudhari** [comment]
@Anshul275 Mention the language

**Comment by Anshul275** [comment]
Python

**Comment by Anshul275** [comment]
@pratik-choudhari 
Where to upload - in python directory or projects directory??
I am also attaching the generated csv file and screenshot of generated csv file.

**Comment by pratik-choudhari** [comment]
@Anshul275 Place it under `Projects` and do not attach the CSV file it will increase the size of repo. A screenshot is enough!
