### ISSUE TITLE
Scalar Product of an Array

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#344]
# Feature ✅

## Description

Given two arrays A1 and A2; Find the Minimum and Maximum Scalar product of these two arrays.
A scalar product is also known as the dot product of two vectors.
 
For finding the minimum scalar product of arrays we need to multiply the minimum value of array to the maximum value of the second array and add all multiple values.
##### Hint: here we need to sort the array1 and array2 in ascending order and descending order respectively.

For finding the maximum scalar product of arrays we need to multiply the minimum value of array to the minimum value of the second array and add these multiple values.
##### Example for Minimum Scalar Product
array 1 : 1 2 3 4
array 2 :  5 3 2 1
scalar product:       1*5+2*3+3*2+4*1 =  5+6+6+4 = 21

##### Example for Maximum Scalar Product
array 1 : 1 2 3 4
array 2 :  2 3 4 5
scalar product:       1*2+2*3+3*4+4*5 =  2+6+12+20 =  40

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by kitteltom** [comment]
@pallavivaswani @pratik-choudhari I would like to do this in Python. Can you assign it to me?

**Comment by AniketDGiri** [comment]
Hello, I would like to do it in C++, Could you please assign this to me?

**Comment by ghanender-chauhan** [comment]
assign me this i will do in python
its my second contribution plz assign me

**Comment by pratik-choudhari** [comment]
@ghanender-chauhan It is assigned to @kitteltom

**Comment by bhavya092** [comment]
Can you assign this to me ? (C++)

**Comment by ShraxO1** [comment]
Can you assign me for python/C/C++

**Comment by MAHIMA01** [comment]
Can you please assign me this issue for JAVA and Python?
