### ISSUE TITLE
Operations on an Array

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#345]
# Feature ✅

## Description

Given a number N, input N elements and the task is to perform the following operations all together: 
- Find the Smallest Number
- Find Largest Element
- Find the sum of all array elements
- Find Frequency of elements
- Count Distinct Elements
- Count Repeating Elements
- Count of Even elements
- Count of odd elements

##### Input: 
12
16 5 8 9 20 4 3 7 8 5 3 2

##### Output: 
Smallest Number: 2
Largest Number: 20
Sum of Array elements = 90
Frequency of elements= 16-1, 5-2, 8-2, 9-1, 20-1, 4-1, 3-2, 7-1, 2-1
Count of distinct elements= 6
Count of repeating elements =  3
Count of Even Elements = 6
Count of odd Elements = 6

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by PriyanshuGangwar** [comment]
Hi, Can I do it in C++?

**Comment by Suraj1199** [comment]
Would like to do in other languages. (Python, C , Java)

**Comment by poojitha2002** [comment]
Hello, I am interested to do this.

**Comment by pallavivaswani** [comment]
> Hello, I am interested to do this.

@poojitha2002 Please mention which language?

**Comment by poojitha2002** [comment]
@pallavivaswani  I would like to do in JAVA

**Comment by poojitha2002** [comment]
@pallavivaswani I am also good at cpp or c..Any language is comfortable to me..Can you please confirm me, which language should I do?

**Comment by AniketDGiri** [comment]
hello, Could you please assign this to me for C++?

**Comment by ankita319** [comment]
Hii!, Can you Assign this c++ project to me?

**Comment by Utkarshn10** [comment]
@pratik-choudhari I would like to do this in Java

**Comment by pratik-choudhari** [comment]
> 
> 
> @pratik-choudhari I would like to do this in Java

It has been already assigned in Java to someone else

**Comment by drashtipatel2503** [comment]
Can I go with python?

**Comment by poojitha2002** [comment]
@pallavivaswani I have added OperationsOnArray .I request you to please check the file and let me know if there are any changes to be done.

**Comment by drashtipatel2503** [comment]
I have done with the task. Any updates required?
