### ISSUE TITLE
Sort an Array

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#346]
# Feature ✅

## Description

Write a program to sort the first half of an array in ascending order and the second half in descending order 

##### Input: 
N = 12
2 6 5 7 0 10 13 9 15 12 1 8
##### Output: 
0 2 5 6 7 10 15 13 12 9 8 1

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by andre-silva-14** [comment]
Could you assign me with TypeScript?

**Comment by ghanender-chauhan** [comment]
i want to work on this please assign me this

**Comment by Himanshu-Nagle** [comment]
@pallavivaswani Kindly please assign me

**Comment by pratik-choudhari** [comment]
@andre-silva-14 Place it under javascript folder.

**Comment by pratik-choudhari** [comment]
@ghanender-chauhan @Himanshu-Nagle language?

**Comment by shree-create** [comment]
can you assign me this issue with C?

**Comment by ghanender-chauhan** [comment]
> @ghanender-chauhan @Himanshu-Nagle language?

Python !!! Assign me please

**Comment by pratik-choudhari** [comment]
@ghanender-chauhan Contribution limit reached.

**Comment by Himanshu-Nagle** [comment]
> @ghanender-chauhan @Himanshu-Nagle language?
C++ and C#

**Comment by pratik-choudhari** [comment]
@Himanshu-Nagle It has been assigned to @shree-create as he mentioned the language, which is asked in the issue at bottom.

**Comment by Himanshu-Nagle** [comment]
> can you assign me this issue with C?

She asked for C. If not possible to assign for C++ then please assign me C#

**Comment by Utkarshn10** [comment]
@pallavivaswani @pratik-choudhari I would like to do it in Java.

**Comment by bhavya092** [comment]
Can you assign this to me? (C++)

**Comment by pratik-choudhari** [comment]
@bhavya092 Its taken in C/C++
