### ISSUE TITLE
Harshad number or not

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#347]
# Feature ✅

## Description

In mathematics, a Harshad number is a number that is divisible by the sum of its digits. 
Input consists of 1 integer.
Example– Number is 21
it is divisible by own sum (1+2) of its digit(2,1)
So it is Harshad number
Some other Harshad numbers are 156,54,120 etc.

## Example

<b>Input:</b>  111
<b>Output:</b>  111 is Harshad
<b>Explanation:</b> 111/(1+1+1) = 37; since 111 is completely divisible by its digits, its Harshad  

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Harshalszz** [comment]
Hey! can I work on this in C++.

**Comment by Himanshu-Nagle** [comment]
@pallavivaswani Kindly please assign me

**Comment by pratik-choudhari** [comment]
@Himanshu-Nagle Language?
@Harshalszz You have been assigned to 2 issues already, it is the max limit for this repo.

**Comment by Ayushmanglani** [comment]
Assign this to me for Python

**Comment by AniketDGiri** [comment]
hello, Could you please assign this to me for C++

**Comment by kusumapriyankaajjarapu** [comment]
Hi, I want to code it in Java. Could you please assignme.

**Comment by Himanshu-Nagle** [comment]
> @Himanshu-Nagle Language?
> @Harshalszz You have been assigned to 2 issues already, it is the max limit for this repo.

C# and PHP

**Comment by kusumapriyankaajjarapu** [comment]
@pratik-choudhari Awaiting your response. 

> Hi, I want to code it in Java. Could you please assignme.

**Comment by carolinejoseph** [comment]
Hey, can I do this problem in C++?
