### ISSUE TITLE
Abundant number or not

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#348]
# Feature ✅

## Description

A number n is said to be Abundant Number to follow these condition:-
 - the sum of its proper divisors is greater than the number itself.
 - And the difference between these two values is called the abundance.
Example:- Abundant number 12 having a proper divisor is 1,2,3,4,6 the sum of these factors is 16 it is greater than 12 so it is an Abundant number.
Some other abundant numbers
    18, 20, 24, 30, 36, 66, 70, 72, 78, 80, 84, 88, 90, 96, 100, 102, 104, 108, 112, 114, 120.. 

## Example

<b>Input: </b>18
<b>Output: </b> 18 is an Abundant Number
<b>Explanation:</b> Divisor of 18 = 1,2,3,6,9 and sum of divisors = 1+2+3+6+9 = 21 which is greater than 18

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Flamer17** [comment]
@pallavivaswani  @pratik-choudhari  I want to do this is JAVA

**Comment by AniketDGiri** [comment]
Hello, I would like to do this in C++.

**Comment by Flamer17** [comment]
I have created a new clean pull request as told for this issuse

**Comment by carolinejoseph** [comment]
Hi, I would like to do this problem in Python

**Comment by KompuDan** [comment]
Hello, I would like to do this in python

**Comment by jayaganeshkumar** [comment]
@pratik-choudhari  can you assign it for java to me?

**Comment by pratik-choudhari** [comment]
@jayaganeshkumar Its assigned to someone else

**Comment by jayaganeshkumar** [comment]
Ok then
