### ISSUE TITLE
Build a google search using a python script

### ISSUE THREAD

**Issue by tusharnankani** [pratik-choudhari/AlgoCode#35]
# Feature ✅

## Description
The script should show the top 10/20 google search results. 

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] This issue will be meaningful for the project.
- [X] I will contribute more in future

**Comment by v-sonawane** [comment]
I am willing to work on this issue. Kindly assign this to me.

**Comment by pratik-choudhari** [comment]
@v-sonawane let me know the language

**Comment by v-sonawane** [comment]
python
