### ISSUE TITLE
Sorting Algorithms

### ISSUE THREAD

**Issue by rajpratyush** [pratik-choudhari/AlgoCode#356]
# Feature ✅
 A python program consisting  of Sorting Algorithms

## Description
I have created a python script which consists of 10 different sorting algorithms implemented as a menu driven program. 
Can I put that in the repository?
 It consists of bubble sort, selection sort, heap sort, merge sort, shell sort etc...

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

**Comment by pratik-choudhari** [comment]
@rajpratyush A similar issue exists, you can contribute to this [issue](https://github.com/pratik-choudhari/AlgoCode/issues/94)
