### ISSUE TITLE
scrape codeforces problem statements

### ISSUE THREAD

**Issue by tusharnankani** [pratik-choudhari/AlgoCode#36]
# Feature ✅

## Description
Build a script to scrape Codeforces problem statements, as per the problem code provided by the user.
Save the result in a text file.

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] This issue will be meaningful for the project.
- [X] I will contribute more in future

**Comment by Blastoise** [comment]
@tusharnankani I will work on this issue so please assign this to me.

**Comment by pratik-choudhari** [comment]
@Blastoise This too will go under `Projects` directory

**Comment by Blastoise** [comment]
Just a query @pratik-choudhari that the by problem statement you mean which of the sections of a problem in codeforces.
Please answer this with precision

**Comment by pratik-choudhari** [comment]
@tusharnankani Please answer.

**Comment by tusharnankani** [comment]
Problem Name, Problem Code, Problem statement, Input, Output, Sample Testcase, Note (usually there, after sample test case)

**Comment by Blastoise** [comment]
@tusharnankani Thanks!
