### ISSUE TITLE
Find Pythagorean Triplet

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#365]
# Feature ✅

## Description

Find the set of Pythagorean triples from the given array
Pythagorean triplets condition: a<sup>2</sup> + b<sup>2</sup> = c<sup>2</sup>

## Example

<b>Input: </b>
[3,4,6,5,7,8]

<b>Output:</b>
[3 4  5]

<b>Explanation: </b>
3<sup>2</sup> + 4<sup>2</sup> = 5<sup>2</sup>

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by sarthak-21** [comment]
@pratik-choudhari assign this issue to me. I will do it in C.

**Comment by sarthak-21** [comment]
@pratik-choudhari Response awaited!

**Comment by KompuDan** [comment]
Hi, i would like to implement this on python, can you asign it to me?

**Comment by harshitalashkari** [comment]
Can you please assign this to me. I'll use Java

**Comment by xcyraxx** [comment]
Can i do this, i can do in Python or Java

**Comment by bhavinisehgal18** [comment]
can you assign me C++

**Comment by pratik-choudhari** [comment]
@bhavinisehgal18 It assigned in C++ to someone else

**Comment by xcyraxx** [comment]
I've pull-requested the python file for pythagorean triplets
