### ISSUE TITLE
Operation On Singly Linked List

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#366]
# Feature ✅

## Description

Perform the following on a Singly Linked List:
- Insert a node in the beginning
- Insert a node at the end
- Insert a node at nth position
- Delete first node
- Delete Last node
- Delete nth node
- Search an element in a linked list

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by kusumapriyankaajjarapu** [comment]
I want to code it in Java. Assign me please.

**Comment by PulkitPansari13** [comment]
Can you assign it to me. Language Python

**Comment by drashtipatel2503** [comment]
Can I code in python?

**Comment by pratik-choudhari** [comment]
@drashtipatel2503 It is already assigned in python to someone else.

**Comment by stuti-ui** [comment]
@pallavivaswani can you assign me this I will use c++

**Comment by drashtipatel2503** [comment]
> @drashtipatel2503 It is already assigned in python to someone else.

With C?

**Comment by pratik-choudhari** [comment]
> 
> 
> > @drashtipatel2503 It is already assigned in python to someone else.
> 
> With C?

Assigned to @stuti-ui based FCFS

**Comment by bhavya092** [comment]
Can you assign this to me? I'll help in C/C++ ...

**Comment by pratik-choudhari** [comment]
@bhavya092 Taken in C/C++
