### ISSUE TITLE
Operations on Doubly Linked List

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#367]
# Feature ✅

## Description

Perform the following on a Doubly Linked List
- Insert a node in the beginning
- Insert a node at the end
- Insert a node at nth position
- Delete first node
- Delete Last node
- Delete nth node

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by kushverma86** [comment]
hey can you assign this to me ?

**Comment by stuti-ui** [comment]
@pallavivaswani can you assign this to me I will use c++.

**Comment by AshwinKul28** [comment]
I would like to pick this in CPP language. can you please assign it to me?

**Comment by pratik-choudhari** [comment]
@kushverma86 Language?

**Comment by barrotsteindev** [comment]
Can you assign me?
I will use C++

**Comment by AniketDGiri** [comment]
Hello, Could you please assign this to me in c++?

**Comment by pratik-choudhari** [comment]
@AniketDGiri You are already assigned to 2 issues which is the limit for this repository.

**Comment by carolinejoseph** [comment]
Hey, can I try this problem in Python?

**Comment by wjyeap123** [comment]
Hi, I would like to work on this problem in JavaScript. Can you assign to me? Thanks.

**Comment by weicheansoo** [comment]
Hi, can I work on this in Java?
