### ISSUE TITLE
Infix to Prefix Conversion

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#368]
# Feature ✅

## Description

Conversion input infix equation to postfix expression

## Example

<b>Input: </b>((a / b) + c) - (d + (e * f ))

<b>Output:</b> -+/abc+d*ef

## Checklist:
- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Flamer17** [comment]
hey, for my 2nd pull req. can you assign this one to me
my first one was Abundant Number Issue 348

ill be using java again

**Comment by PriyanshuGangwar** [comment]
hey, can you assign this to me in C++ ??

**Comment by ghanender-chauhan** [comment]
asiign me this i will do in python

**Comment by harshitalashkari** [comment]
Hey can you assign this o me!! I'll use Java
