### ISSUE TITLE
Postfix to Prefix Conversion

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#369]
# Feature ✅

## Description

Conversion input infix equation to postfix expression

## Example

<b>Input:</b> XY+UV-/
<b>Output:</b> /+XY-UV

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by uddeshyatyagi** [comment]
@pratik-choudhari ,please assign this to me, i have already worked on it.
#373 
Thank you
