### ISSUE TITLE
build a stock scraper

### ISSUE THREAD

**Issue by tusharnankani** [pratik-choudhari/AlgoCode#37]
# Feature ✅

## Description
Scrape the S&P 500 Companies list from Wikipedia, Yahoo Finance, etc., then output the data.
Get stock prices.
HINT: `yfinance`, `nsepy` libraries in Python.

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] This issue will be meaningful for the project.
- [X] I will contribute more in future

**Comment by Skr-suyash** [comment]
Please edit your question to be more precise. Do we need to show the stock prices of all 500 Companies as it would be huge. Also what format the data should be - a DataFrame or txt file output.

**Comment by tusharnankani** [comment]
Build a simple web scraper that collects information about the 500 companies listed in the S&P index. Load it into a .csv file.

**Comment by Skr-suyash** [comment]
I would like to work on this in Python. Please assign this to me.
