### ISSUE TITLE
scrape codechef problem statements

### ISSUE THREAD

**Issue by tusharnankani** [pratik-choudhari/AlgoCode#38]
# Feature ✅

## Description
Build a script to scrape Codechef problem statements, as per the problem code provided by the user.
Scrape the following:
Problem Name, Problem Code, Problem statement, Input, Output, Sample Testcase, Note (usually there, after sample test case)
Save the result in a text file.

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] This issue will be meaningful for the project.
- [X] I will contribute more in future

**Comment by andre-silva-14** [comment]
I could work on this with Python, but I will need a clear problem description, this one is way too vague.

**Comment by pratik-choudhari** [comment]
@tusharnankani

**Comment by tusharnankani** [comment]
I edited the Problem Statement yesterday itself. Let me know what more details you want to know! @andre-silva-14

**Comment by andre-silva-14** [comment]
@tusharnankani That's great! I think it is clearer now, thank you.

@pratik-choudhari Could you assign the issue to me? Thank you!
