### ISSUE TITLE
Minimun swaps to make a palindrome

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#4]
# Feature ✅

## Description

Write a program to calculate minimum number of swaps required to make a string palindrome.

## Example
Input: niitn
Output: 1

Input: deideif
Output: 2 
Explanation: swap 1->(d,f), swap 2-> (e, i)
__Mention programming language while requesting assignment__

**Comment by nits01** [comment]
Assign it to me.
Language : JAVA

**Comment by devangmukherjee** [comment]
I would like to work on the C++ version of this  @pratik-choudhari

**Comment by Khalleud** [comment]
I would like to make it with python
