### ISSUE TITLE
Bit array

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#405]
# Feature ✅

## Description
Given four integers N,S,P,Q, calculate the number of distinct elements in array `a` calculated using the following pseudo code:
<pre>
a[0] = S (modulo 2^31)
for i = 1 to N-1
    a[i] = a[i-1]*P+Q (modulo 2^31) 
</pre>

## Example
Input: 3 1 1 1
Output: 3

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by kitteltom** [comment]
@pratik-choudhari I can do that in Java. Can you please assign it to me?

**Comment by anshika0207** [comment]
@pratik-choudhari can you assign this to me? I can code in c++.

**Comment by namita2310** [comment]
@pratik-choudhari can you assign this to me? I can code in c.

**Comment by anu-ragi** [comment]
hi, i can try in javascript.. can u pls assign..

**Comment by codeit-dotcom** [comment]
can you assign this to me ? i can code in c++
