### ISSUE TITLE
Hotel prices

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#406]
# Feature ✅

## Description
A hotel has two types of room standard and luxury. Every customer mentions the number of bedrooms and bathrooms required for that particular room.
```
Cost of standard room = 5 * bedrooms + 2 * bathrooms

Cost of luxury room = cost of standard room for same bedrooms and bathrooms + 200
```
The task is to print the total cost of rooms requested.  

## Example
First line will be the number of test cases. Room data format `room-type bedrooms bathrooms`.
There can be any number of standard and luxury rooms.

Input:
2
standard 3 1
luxury 1 1

Output:
224

Explanation:
Standard fee: `(5 * 3 + 2 * 1)`
luxury: `(5 * 1 + 2 * 1) + 200`
total = standard + luxury

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by therealkiddo** [comment]
Hi, regarding the output of the example case mentioned, shouldn't the output be 224?

**Comment by A-Annan** [comment]
Can I work on it ?

**Comment by anshika0207** [comment]
@pratik-choudhari can you assign this to me? I can code in c++

**Comment by gaurangagarwal** [comment]
I would like to work on this issue. Can you assign me for Java ?

**Comment by pratik-choudhari** [comment]
@therealkiddo I have added the explanation check it out.

**Comment by gaurangagarwal** [comment]
> Hi, regarding the output of the example case mentioned, shouldn't the output be 224?

Agreed.

**Comment by pratik-choudhari** [comment]
@A-Annan Lang?

**Comment by gaurangagarwal** [comment]
Hi @pratik-choudhari ,
The second test case is `luxury 1 1`, which means the number of bed rooms is 1 and bathrooms is 1. In the `explanation` section, you have considered the bedrooms and bathrooms as 3 and 1 respectively even for Luxury rooms (may be based on the 1st test case). Can you please clarify ?

**Comment by pratik-choudhari** [comment]
@anshika0207 I mistakenly assigned you to this issue. You are already assigned to 2 issues which is the limit to this repository.

**Comment by pratik-choudhari** [comment]
@gaurangagarwal @therealkiddo Mistake from my side, rectified now. Thanks for bringing that up!👏

**Comment by amulya12** [comment]
can you assign it to me. I can code in JAVA

**Comment by ShubhamNagure** [comment]
Hi @pratik-choudhari 
Please assign me this task

**Comment by pratik-choudhari** [comment]
@ShubhamNagure Lang

**Comment by ShubhamNagure** [comment]
> @ShubhamNagure Lang

Python3 or Java.
Whichever you prefer.

**Comment by ShubhamNagure** [comment]
> > @ShubhamNagure Lang
> 
> Python3 or Java.
> Whichever you prefer.

Hi @pratik-choudhari ,
Task completed.
Please check and review #432 PR.
Thanks for the opportunity.

**Comment by manojrao3619** [comment]
Hi @pratik-choudhari , 
can you assign it to me for C++/JavaScript.

**Comment by ananthalakshmiragi** [comment]
hi, can do it in java or javascript. Please assign.

**Comment by pratik-choudhari** [comment]
@manojrao3619 C++ and @ananthalakshmiragi Js
