### ISSUE TITLE
Last digit of Squared Fibonacci sequence

### ISSUE THREAD

**Issue by atharvakarnik** [pratik-choudhari/AlgoCode#410]
# Feature ✅

## Description
Write a program to compute the sum of the squared Fibonacci sequence. <br>
The program takes input of natural number 'n', and must compute F<sub>0</sub><sup>2</sup>+F<sub>1</sub><sup>2</sup>+F<sub>2</sub><sup>2</sup>+...+F<sub>n</sub><sup>2</sup> 
The output should be the last digit of this summation.

#### NOTE:
Be careful while implementing the program as naive approaches (like recursion) have a time complexity of O(2<sup>n</sup>)

## Example
Input:
 7
Output:
 3

## Explanation
0 + 1 + 1 + 4 + 9 + 25 + 64 + 169 = 273
Thus, last digit is 3

## Checklist:

- [ ] I have read the project guidelines.
- [ ] I have checked all the existing projects, before submitting a new project issue.
- [ ] This issue will be meaningful for the project.
- [ ] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__
__As python implementation of this algorithm has already been done in request #401, feel free to go for other programming languages__

**Comment by PriyanshuGangwar** [comment]
Hi, Can you assign this in C++ ?

**Comment by pratik-choudhari** [comment]
@PriyanshuGangwar You are already assigned to 2 issues, that's the limit for this repository.

**Comment by cmeyrueix4** [comment]
Hey, can you assign this to me in Java?

**Comment by SalmaBliss** [comment]
Hey, Can you assign this to me in C# ?

**Comment by codeit-dotcom** [comment]
Can you assign this to me? i will do in C++

**Comment by anu-ragi** [comment]
Hi, I would like to do this in Javascript. Pls assign.

**Comment by anu-ragi** [comment]
Is this closed for assignees also?

**Comment by pratik-choudhari** [comment]
@anu-ragi Nope.
