### ISSUE TITLE
N-Queen Problem

### ISSUE THREAD

**Issue by pallavivaswani** [pratik-choudhari/AlgoCode#444]
# Feature ✅

## Description

The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other. 

## Example

<b>Input:</b> N=4
<b>Output:</b> 
4 Queen problem
<pre>{ 0,  1,  0,  0}
{ 0,  0,  0,  1}
{ 1,  0,  0,  0}
{ 0,  0,  1,  0}</pre>

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by manojrao3619** [comment]
Hi @pallavivaswani,
can you assign me for C++.

**Comment by ShraxO1** [comment]
Can you assign me for Python.

**Comment by aniket173000** [comment]
Can you please assign me this issue . I can do it in C or C++ .

**Comment by pratik-choudhari** [comment]
@aniket173000 It is assigned to @manojrao3619 in C/C++

**Comment by pavleen14** [comment]
Hey @pallavivaswani Can you assign this to me? I will provide a solution in JAVA.

**Comment by namrata18s** [comment]
could you assign this issue to me, can provide solution in c, cpp, java

**Comment by pavleen14** [comment]
> Hey @pallavivaswani Can you assign this to me? I will provide a solution in JAVA.

I have submitted the solution to issue #444. Kindly review and merge it. @pratik-choudhari
