### ISSUE TITLE
Closest Pair Of Points

### ISSUE THREAD

**Issue by Nishitk-20** [pratik-choudhari/AlgoCode#450]
# Feature ✅

## Description
An array of n points in the plane, and the problem is to find out the closest pair of points in the array.

## Example
  __Input__ : 
         N = 6
         Array =[ {2, 3}, {12, 30}, {40, 50}, 
                      {5, 1}, {12, 10}, {3, 4} ] 

 __Output__ : 
        Smallest Distance = 1.414214

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Nishitk-20** [comment]
I will like to solve this using cpp

**Comment by vksingh25** [comment]
I would like to solve this using CPP

**Comment by RachanaKampli** [comment]
can you assign this to me to in python?
