### ISSUE TITLE
Distinct Permutations Of the String

### ISSUE THREAD

**Issue by Nishitk-20** [pratik-choudhari/AlgoCode#456]
# Distinct Permutations Of the String
# Feature ✅

## Description
To print all the possible permutations of the String which are different, that is, no permuatations are repeated
A permutation, also called an “arrangement number” or “order,” is a rearrangement of the elements of an ordered list S into a one-to-one correspondence with S itself. A string of length n has n! permutation.

## Example

Input:  str[] = "ABCA"
Output: AABC AACB ABAC ABCA ACBA ACAB BAAC BACA 
            BCAA CABA CAAB CBAA

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Nishitk-20** [comment]
I will like to do it using cpp

**Comment by wjyeap123** [comment]
Hi, I would like to do this in Python
