### ISSUE TITLE
Nth Node from The end Of the LinkedList

### ISSUE THREAD

**Issue by Nishitk-20** [pratik-choudhari/AlgoCode#472]
# Feature ✅

## Description

Given a Linked List and a number n, write a program that prints the value at the n’th node from the end of the Linked List.
## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Nishitk-20** [comment]
I will like to solve this using cpp

**Comment by pratik-choudhari** [comment]
@Nishitk-20 A similar issue has already been implemented.
