### ISSUE TITLE
Code crashing when divide by 0

### ISSUE THREAD

**Issue by rodrigo-br** [pratik-choudhari/AlgoCode#479]
# Bug 🐞

## Description
It's just something to atempt it. When user input a 0 and ask for a division, it return an error.

## Example
def _div(left: int, right: int) -> int:
  return left / right
  if left == 0 or right == 0:  # This is an important thing too, so the the code don't outcome an error
     print('Unable to divide by zero')
  else:
     return left / righ

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__in a Python calculator code__

**Comment by pratik-choudhari** [comment]
@rodrigo-br Great, can you make a PR?

**Comment by rodrigo-br** [comment]
@pratik-choudhari done! Is my first PR so if theres something wrong, please let me know.
