### ISSUE TITLE
Armstrong number

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#48]
# Feature ✅

## Description
For a given number n find all armstrong numbers less than n
An Armstrong number is the one whose sum of mth power of every digit in the number is equal to number itself, where m is the length of number

for 371:  3<sup>3</sup> + 7<sup>7</sup> + 1<sup>3</sup> = 371

## Example
Input: 1000
Output: 1, 2, 3, 4, 5, 6, 7, 8, 9, 370, 371, 407

__Mention language while requesting assignment__

**Comment by ayu16** [comment]
please assign this to me...

**Comment by pratik-choudhari** [comment]
@ayu16 Mention language as it is mentioned in the issue.

**Comment by ayu16** [comment]
I can do it in c++ and python 
please assign this to me

**Comment by ayu16** [comment]
java and c# too

**Comment by pratik-choudhari** [comment]
@ayu16 Only one language for a problem! Read CODE_OF_CONDUCT

**Comment by ayu16** [comment]
I can write in any language mentioned above

**Comment by pratik-choudhari** [comment]
@ayu16 assigned for python

**Comment by Anshul275** [comment]
Assign me for C++

**Comment by pratik-choudhari** [comment]
@Anshul275 for c++

**Comment by 2tanayk** [comment]
I've already contributed to a problem in your repo,if you want Im ready to do it in Java @pratik-choudhari  :)

**Comment by instareasy** [comment]
yup ! i can work on this in java.

**Comment by 2tanayk** [comment]
I have the Java code for it ,if you want I can PR @pratik-choudhari ,sorry I was a bit busy with my college work since tests are nearby :(

**Comment by pratik-choudhari** [comment]
@2tanayk No issues. You can PR now.

**Comment by amanraj862** [comment]
hey i can code this in java please assign me this

**Comment by Ishaan-0098** [comment]
Please assign this to me , my awesomeness will be presented in python

**Comment by pratik-choudhari** [comment]
@Ishaan-0098 @amanraj862 Java and Python have already been assigned.

**Comment by amanraj862** [comment]
> @Ishaan-0098 @amanraj862 Java and Python have already been assigned.

okay

**Comment by SaloniK17** [comment]
Can you please assign to me for c?
Thank you

**Comment by pratik-choudhari** [comment]
@SaloniK17 this issue has been assigned in C.

**Comment by SaloniK17** [comment]
@pratik-choudhari but you haven't assigned  this issue in c to anybody else .so, please can i do this?

**Comment by pratik-choudhari** [comment]
@SaloniK17 C and C++ are not distinguished.

**Comment by SaloniK17** [comment]
@pratik-choudhari  Okay
