### ISSUE TITLE
Measures of central tendency

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#49]
# Feature ✅

## Description
For a given set of numbers calculate the Mean, Median and Mode

## Example
Input: 8 9 4 6 7 25 44 6 8 15
Output: Mean: 13.2
Median: 8
Mode: 8, 6

__Note: Look out for length of input it affects calculation of median and don't forget to sort the input!__
__Mention your language in comment__

**Comment by srushtips** [comment]
Can I work on this? Thank you!

**Comment by srushtips** [comment]
I will work using Java
