### ISSUE TITLE
Find the single element

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#5]
# Feature ✅

## Description
Find the only word that appeared single time in the input

## Example
Input:  red
          animal
          bird
          animal
          bird

Output: red

Hint: Make use of bit-wise operation
__Mention programming language while requesting assignment__

**Comment by tmw9** [comment]
I can take this up

**Comment by pratik-choudhari** [comment]
@tmw9 Please mention language as it is mentioned in issue!

**Comment by tmw9** [comment]
C++

**Comment by tmw9** [comment]
Just one doubt @pratik-choudhari , other elements will appear exactly twice?

**Comment by ReyhanSara** [comment]
Hi there! Can I work on this using Java?

**Comment by pratik-choudhari** [comment]
Yes, sure!

**Comment by alvinuday** [comment]
Hi, I would like to propose a code for this question in python , Can you please assign it to me
