### ISSUE TITLE
Selection Sort in Java

### ISSUE THREAD

**Issue by srushtips** [pratik-choudhari/AlgoCode#50]
# Feature ✅

## Description

Creating a sorting folder in Java to include sorting algorithms. 
## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

**Comment by srushtips** [comment]
Can this be assigned to me? Thanks!

**Comment by pratik-choudhari** [comment]
@srushtips Sure, I had just added a similar issue. But in that you had option to switch between sorting algorithms. Nonetheless, go ahead.

**Comment by srushtips** [comment]
oh, my bad!
