### ISSUE TITLE
Let's sort it out v1.0

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#52]
# Feature ✅

## Description
The task is to implement:
* Insertion sort
* Selection sort
* bubble sort

## Example
First input will be name of algorithm followed by list of integers in next line.
Input: Selection 
1 8 3 9 33 02 0 93 64 22 1 35

Output: sorted list of input

__You are encourage not to copy code from online sources just for the name of open source contribution__

__Mention language in comments__

**Comment by AmyWeitzman** [comment]
@pratik-choudhari I'd like to work on this

**Comment by Awanit512** [comment]
I would like to do this in C++.

**Comment by tejaswini22199** [comment]
I would like to do this in JAVA @pratik-choudhari

**Comment by codermind-divya** [comment]
Can I work on this in C++?

**Comment by pratik-choudhari** [comment]
@codermind-divya This code has been assigned to @Awanit512 for C++, you can take up Java.

**Comment by codermind-divya** [comment]
I am not well-versed with Java. No problem! I'll take up another issue.

**Comment by dhrubajyoti89** [comment]
Can i work with java? @pratik-choudhari
