### ISSUE TITLE
número perfecto🕶

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#53]
# Feature ✅

## Description
Find all perfect number less than n

a perfect number is a positive integer that is equal to the sum of its positive divisors, excluding the number itself. For instance, 6 has divisors 1, 2 and 3 (excluding itself), and 1 + 2 + 3 = 6, so 6 is a perfect number. 

## Example
Input: 500

Output: 6 28 496

__Note: perfect numbers value escalate quickly, checkout the list [here](https://en.wikipedia.org/wiki/List_of_perfect_numbers)__

**Comment by 2tanayk** [comment]
If you want I can work on this using Java or C (I prefer Java ) ,assign me if possible

**Comment by pratik-choudhari** [comment]
@2tanayk A contributor can PR for max 2 problems.

**Comment by 2tanayk** [comment]
I have contributed to 1,the regenerating min. Array one,so the other one was Armstrong no but it got closed right?

**Comment by 2tanayk** [comment]
Ok sorry,it was re-opened didn't see ty👍✌️

**Comment by alvinuday** [comment]
Hi, i would like to code a solution in python, Can you please assign it to me ?

**Comment by alvinuday** [comment]
Hi, i would like to code a solution in python, Can you please assign it to me ?
