### ISSUE TITLE
Measures of dispersion

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#56]
# Feature ✅

## Description
Calculate measures of dispersion for given distribution.
Measures of dispersion:
* Range
* Variance
* Standard Deviation

## Example
Input: 238,139,171,234,171,152,170,233,105,260

Output(2 decimal precision): 
Range: 155
Variance: 2330.81
Standard deviation: 48.27

__Mention language in comment__

**Comment by Swarn10** [comment]
@pratik-choudhari  I would love to contribute to this. Please assign it to me as I believe I can do full justice to it. I can implement the solution in C++ and Python.

**Comment by pratik-choudhari** [comment]
@Swarn10 Only one language per problem

**Comment by Swarn10** [comment]
@pratik-choudhari  Please assign it to me. I will implement the solution in C++. Will be happy to help.

**Comment by AlexNorth-PNG** [comment]
I would like to work on this problem using Java
