### ISSUE TITLE
Maximum Depth of N-ary Tree

### ISSUE THREAD

**Issue by arnabchakraborty97** [pratik-choudhari/AlgoCode#57]
# Feature ✅

## Description
Given a n-ary tree, find its maximum depth.

The maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.

Nary-Tree input serialization is represented in their level order traversal, each group of children is separated by the null value.

## Example
Example 1:

![image](https://user-images.githubusercontent.com/35025410/94951303-a833b800-0501-11eb-8799-b249f5d6f0f8.png)

Input: root = [1,null,3,2,4,null,5,6]
Output: 3

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

**Comment by arnabchakraborty97** [comment]
@pratik-choudhari Please check the issue and assign me if possible. Thanks!

**Comment by pratik-choudhari** [comment]
@arnabchakraborty97 Language?

**Comment by arnabchakraborty97** [comment]
@pratik-choudhari Python

**Comment by sauravUppoor** [comment]
@arnabchakraborty97 Tree given in example 1 isn't abinary tree, is it?

**Comment by arnabchakraborty97** [comment]
> @arnabchakraborty97 Tree given in example 1 isn't a binary tree, is it?

Yes, my mistake with the title.

**Comment by paraggoyal28** [comment]
@pratik-choudhari  can I do this task  in c++

**Comment by pratik-choudhari** [comment]
@paraggoyal28 You can only contribute to max two issues. Confirm from your previous problems you want to work on.

**Comment by paraggoyal28** [comment]
@pratik-choudhari  ok I have checked two issues from previous problems. You can assign this to some one else.
