### ISSUE TITLE
Searching Tree Algorithm Codes

### ISSUE THREAD

**Issue by Ritesh055** [pratik-choudhari/AlgoCode#58]
# Feature ✅
Inclusion of searching tree algorithms in the C/C++ codes.

## Description
The search tree methods include Binary Search Tree, AVL Tree, Tries, B Trees, OS Trees, Interval Trees.

## Checklist:

- [ X] I have read the project guidelines.
- [ X] I have checked all the existing projects, before submitting a new project issue.
- [X ] This issue will be meaningful for the project.
- [ X] I will contribute more in future

**Comment by pratik-choudhari** [comment]
@Ritesh055 Could be a little more specific in the issue? Like what will the code do, will all be in a single file and stuff?

**Comment by Ritesh055** [comment]
The code includes different files for each of these searching trees and will attempt to explain the basic functionality of each of these algorithms.
[Searching Trees.docx](https://github.com/pratik-choudhari/AlgoCode/files/5319594/Searching.Trees.docx)

**Comment by jyotiGambhir** [comment]
Can you assign it to me? I would like to implement search in trie in CPP

**Comment by pratik-choudhari** [comment]
@jyotiGambhir @Ritesh055 has made PR for the same.
