### ISSUE TITLE
Add Code for LCS of 2 strings

### ISSUE THREAD

**Issue by snape-here** [pratik-choudhari/AlgoCode#59]
#Feature ✅

## Description
Code for LCS of 2 strings missing

## Example
Input:
s = "axa"
t = "aa" 

Output:
aa

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

**Comment by tejaswini22199** [comment]
Hey can I work on this issue?

**Comment by snape-here** [comment]
> 
> 
> Hey can I work on this issue?

I already added C++ solutions to the problem. You can try adding solutions in Different Languages.
