### ISSUE TITLE
Are these two anagrams?

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#6]
# Feature ✅

## Description
A word is an anagram of another if they have same characters but in a different order.

## Example
Input: listen silent
Output: Yes

Input: abcd abcdd
Output: No

## Improvement:
If second word is an anagram check if it is a valid English word

**Comment by utkarshbajaj** [comment]
Hey, I'd like to do this

**Comment by tejaswini22199** [comment]
Hey @pratik-choudhari  I can do it in JAVA. Pls assign it to me.

**Comment by pratik-choudhari** [comment]
@tejaswini22199 You have already taken up #10 and #32 and one contributor can make max 2 PRs.

**Comment by tejaswini22199** [comment]
Yes Fine . I just mentioned all that I know so that I may be assigned any two.

**Comment by statst** [comment]
Can I contribute. Language : Javascript

**Comment by Mayank662** [comment]
Hi @pratik-choudhari I would like to work on this issue in Python.

**Comment by pratik-choudhari** [comment]
@Mayank662 @statst Please follow directory structure as per CODE_OF_CONDUCT
