### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#7]
# Feature ✅

## Description
Create a calculator that takes input from command line and outputs in the same window

## Example
Input: 1
+
2
Output: 3

__Note: This Calculator is a basic one, add your own new ideas such as trignometric functions, sqrt, log, square, exponents, etc. Or make it into a GUI!__
__Mention programming language while requesting assignment__

**Comment by DarkCode01** [comment]
@pratik-choudhari  Can I contribute to this?

**Comment by comrade-om** [comment]
Hi, I would be happy to build a calculator in javascript (Node.js)! Shall I start working on it?

**Comment by pratik-choudhari** [comment]
@comrade-om Sure! Start working on it 🙌

**Comment by comrade-om** [comment]
Hi again, I have been observing this repo for a while, since nobody has added a calculator in C++ yet, shall I contribute the same @pratik-choudhari ?

**Comment by pratik-choudhari** [comment]
@comrade-om A contributor can contribute only once to a problem. You can try issues.

**Comment by comrade-om** [comment]
Alright thanks :smile:

**Comment by pallavivaswani** [comment]
Hey @pratik-choudhari, Can I contribute to this? 
I can provide a GUI for simple + scientific calculator in Python

**Comment by pratik-choudhari** [comment]
Sure! Start working on it 🙌
