### ISSUE TITLE
Sorting Algorithms in C++

### ISSUE THREAD

**Issue by Ritesh055** [pratik-choudhari/AlgoCode#75]
# Feature ✅
I wish to add a seperate file for each sorting method

## Description
This includes Bubble Sort, Selection Sort, Insertion Sort, Shell Sort, Merge Sort

## Checklist:

- [ X] I have read the project guidelines.
- [ X] I have checked all the existing projects, before submitting a new project issue.
- [ X] This issue will be meaningful for the project.
- [ X] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by ayu16** [comment]
can I please be assigned to this task I can do it in python

**Comment by kalpita01** [comment]
Can i try working on this issue? My programming language would be c++

**Comment by kartickgupta** [comment]
Hey @Ritesh055  ! Can I also work over this ?

**Comment by Ritesh055** [comment]
@kartickgupta I don't assign the issue. @pratik-choudhari will do that.

**Comment by kartickgupta** [comment]
Okay !!!

**Comment by kartickgupta** [comment]
@pratik-choudhari can you please assign me this, I'll do it in C++ ?

**Comment by ayu16** [comment]
I created a separate file for each sort in python...

**Comment by pratik-choudhari** [comment]
@kartickgupta @kalpita01 is already assigned for C++, if you wish to do you are free to do so. The first c++ PR will be merged.
