### ISSUE TITLE
Math expression evaluation

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#8]
# Feature ✅

## Description
Write a program which can evaluate mathematical expressions in infix format.

## Example
Input: 2 + 3 * ( 4 - 2 )
Output: 8

__Note: Use stack__
__Mention programming language while requesting assignment__

**Comment by AnweshaDan** [comment]
I would like to solve this using C++. Could you please assign this to me ?

**Comment by AlekhyaPoosapati** [comment]
i want to write that in c++ using stacks can you please assign to me

**Comment by sid-1207** [comment]
I would like to contribute in C
Please assign it to me

**Comment by pratik-choudhari** [comment]
@sid-1207 It has been already assigned in C

**Comment by sid-1207** [comment]
@pratik-choudhari What about C++?
Do you need it

**Comment by pratik-choudhari** [comment]
@sid-1207 C and c++ are not distinguished.
