### ISSUE TITLE
To-do app🧾

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#80]
# Feature ✅

## Description
Build a to-do app with a web interface in either Js or python

## Example
User must be able to add tasks in the web interface and If a task is done mark it as done(dim the text or strike the text)
For this task it is mandatory to add the screenshot of resultant website with all possible cases inside README file.

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by manasivaraiya** [comment]
I'd like to contribute to this in javascript

**Comment by ShivamYadav-Coding** [comment]
I would like to work on it.
Here is my Todo List. And i will also like to improve it further.
![Screenshot (13)](https://user-images.githubusercontent.com/59358990/94990447-d533a980-0599-11eb-932e-f84c5d0d3593.jpg)
![Screenshot (14)](https://user-images.githubusercontent.com/59358990/94990448-d664d680-0599-11eb-8d85-0e5377654c94.jpg)
![Screenshot (11)](https://user-images.githubusercontent.com/59358990/94990449-d6fd6d00-0599-11eb-9a73-c84a47b5ffe8.jpg)

**Comment by pratik-choudhari** [comment]
@manasivaraiya You are up, @ShivamYadav-Coding which language have you used?

**Comment by ShivamYadav-Coding** [comment]
I used Javascript in it.

**Comment by pratik-choudhari** [comment]
@manasivaraiya Has already been assigned for javascript, you can check after a few days.

**Comment by ShivamYadav-Coding** [comment]
Sure!

**Comment by Ishaan-0098** [comment]
hi, please assign this task to me i can develop a python code for the UI and the functionality of the windows application
