### ISSUE TITLE
Mini photo editor🖼

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#82]
# Feature ✅

## Description
A program to perform following operations on an input image:
* Enhance Sharpness 
* Enhance Colour
* Blur
* Resize
* Black and white filter
* Sepia filter

## Example
The program must be menu driven at least. GUI or a Web interface would be excellent👏

__This contribution will go under `Projects` folder.__
__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by Skr-suyash** [comment]
Can I work on this issue. I will work in HTML, CSS and Javascript and create an ImageEditor website.

**Comment by pratik-choudhari** [comment]
@Skr-suyash Place everything under `Projects` folder.
