### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by ShivamYadav-Coding** [pratik-choudhari/AlgoCode#83]
I would like to add my project of **weather App**.

## Description
Currently it looks like this :- 
![Screenshot (15)](https://user-images.githubusercontent.com/59358990/94990897-e92cda80-059c-11eb-99e6-3968a6930cc1.jpg)
![Screenshot (16)](https://user-images.githubusercontent.com/59358990/94990898-ea5e0780-059c-11eb-9028-29084a7e021e.jpg)

**After adding this project i will work on it and improve it's UI and features.**
**Stack that i used to make this project :-** 
1. HTML
2. CSS
3. JavaScript
4. NodeJs

It is a good beginners project in Web Development.

**Comment by ShivamYadav-Coding** [comment]
@pratik-choudhari Could i work on this?

**Comment by pratik-choudhari** [comment]
@ShivamYadav-Coding Done.

**Comment by pratik-choudhari** [comment]
@ShivamYadav-Coding Let me know the language

**Comment by ShivamYadav-Coding** [comment]
Main language is JavaScript.

**Comment by ShivamYadav-Coding** [comment]
Projected is submitted.
Pull request : #92 
I will make good UI changes soon.

**Comment by pratik-choudhari** [comment]
@ShivamYadav-Coding Your work is commendable,

**Comment by ShivamYadav-Coding** [comment]
Thank you very much :)

**Comment by pratik-choudhari** [comment]
@ShivamYadav-Coding I have received github security warnings about the version of package used in the project. Check them out in security and update ASAP.

**Comment by ShivamYadav-Coding** [comment]
ok i will fix it as soon as possible.

**Comment by ShivamYadav-Coding** [comment]
Just made some UI changes to weather app and also deployed the app to heroku so that anyone could visit it. Please give it a look.
Pull Request : #140

**Comment by pratik-choudhari** [comment]
@ShivamYadav-Coding Loved it!

**Comment by ShivamYadav-Coding** [comment]
Hello i just implemented feature to pin weather for a location in weather app
Pull request : #171
