### ISSUE TITLE
Find the Pth term in A.P

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#9]
# Feature ✅

## Description
Given m<sup>th</sup> and n<sup>th</sup> term of an AP, find the p<sup>th</sup> term

## Example
Format: m n  m<sup>th</sup>term n<sup>th</sup>term p
Input: 6 10 12 20 5
Output: 10
__Mention programming language while requesting assignment__

**Comment by vedanthv** [comment]
Hi, which language can I code in?

**Comment by ankitgoel25** [comment]
@pratik-choudhari I would like to work on this issue.

**Comment by ankitgoel25** [comment]
Sorry to say but your question is wrong. If you want to find pth term then the output should be 10 and if you want to find **sum of pth terms** then the answer would be 30

**Comment by pratik-choudhari** [comment]
My mistake @ankitgoel25, sum and term sounds good!

**Comment by pratik-choudhari** [comment]
@vedanthv Python, Java, C, C++

**Comment by ankitgoel25** [comment]
Hi @pratik-choudhari , this is my first time contributing to Hactoberfest and open source as well. I made a pull request for the issue in C++ language. Please review my PR and do tell me if I need to do some corrections.
Thank You

**Comment by DevanshD3** [comment]
Hey I would like to code the python version of it!

**Comment by instareasy** [comment]
I would like to code the solution for this set in JAVA.

**Comment by pratik-choudhari** [comment]
@DevanshD3 assigned for python, @instareasy assigned for java
