### ISSUE TITLE
Let's sort it out v2.0

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#94]
# Feature ✅

## Description
The task is to implement:
* Merge sort
* Shell sort
* Radix sort

## Example
First input will be name of algorithm followed by list of integers in next line.
Input: Shell
1 8 3 9 33 02 0 93 64 22 1 35

Output: sorted list of input

__You are encourage not to copy code from online sources just for the name of open source contribution__

__Mention language in comments__

**Comment by kartickgupta** [comment]
Merge Sort and Radix Sort in C++, Will it work @pratik-choudhari  ?

**Comment by verma-pulkit** [comment]
I would like to contribute for CPP.

**Comment by pratik-choudhari** [comment]
@verma-pulkit It's already assigned for c++, can you use another language?

**Comment by shash29999** [comment]
@pratik-choudhari pls assign me in JAVA.

**Comment by alvinuday** [comment]
Hi, I would like to use Python to write the code for these algorithms, could you please assign it to me

**Comment by rajpratyush** [comment]
Can you please assign me this issue?

**Comment by pratik-choudhari** [comment]
@rajpratyush You could take up python, c#, js.

**Comment by rajpratyush** [comment]
@pratik-choudhari i would like to take Python

**Comment by rajpratyush** [comment]
@pratik-choudhari Can you assign me this issue?
