### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#95]
# Feature ✅

## Description
A program to perform the following with two complex numbers A, B:
* addition, A + B
* subtraction, A- B
* multiplication, A * B
* division, A / B
* mod(A)
* mod(B)

## Example
First input will be 1st number with real and imaginary part similarly second number.

Input: 
2 1
5 6

Output:
7.00+7.00i
-3.00-5.00i
4.00+17.00i
0.26-0.11i
2.24+0.00i
7.81+0.00i

__You are encourage not to copy code from online sources just for the name of open source contribution__

__Mention language in comments__

**Comment by kartickgupta** [comment]
@pratik-choudhari  Please, assign me in C++!!

**Comment by Ace117MC** [comment]
Please assign this to me in python

**Comment by naman-150200** [comment]
please assign this to me in c++

**Comment by shash29999** [comment]
@pratik-choudhari , pls assign me JAVA

**Comment by kinshukdua** [comment]
@pratik-choudhari kindly assign this issue to me in Javascript
