### ISSUE TITLE
Valid credit card number

### ISSUE THREAD

**Issue by pratik-choudhari** [pratik-choudhari/AlgoCode#96]
# Feature ✅

## Description
Find if entered credit card number is valid number.
Conditions for a valid credit card number:
► It must start with a 4, 5 or 6.
► It must contain exactly 16 digits.
► It must only consist of digits (0-9).
► It may have digits in groups of 4, separated by one hyphen "-".
► It must NOT use any other separator like ' ' , '_', etc.
► It must NOT have 4 or more consecutive repeated digits. 

## Example
Input: 4253625879615786
Output: Yes

Input: 5122-2368-7954-3214
Output: Yes

Input: 42536258796157867 
Output: No

Input: 44244x4424442444  
Output: No

__Contributors are supposed to mention their coding language while asking for assignment__

**Comment by ronanren** [comment]
can i assigned to this task ? and what's language what your want ?

**Comment by pratik-choudhari** [comment]
@ronanren Java, py, c/c++, js

**Comment by comrade-om** [comment]
I would be glad to work on this in javascript @pratik-choudhari

**Comment by Diegoslourenco** [comment]
Can I solve this in py?

**Comment by ronanren** [comment]
I can do it in js and cs.

**Comment by XoMute** [comment]
I will do it in java @pratik-choudhari

**Comment by barrotsteindev** [comment]
I can do it in c++

**Comment by pratik-choudhari** [comment]
@comrade-om Javascript
@Diegoslourenco Python
@ronanren C
@XoMute Java
@barrotsteindev c++

**Comment by comrade-om** [comment]
Please review my PR @pratik-choudhari :pray:
